; Listing generated by Microsoft (R) Optimizing Compiler Version 19.16.27050.0 

include listing.inc

INCLUDELIB OLDNAMES

PUBLIC	??_C@_0P@IDHECIDN@NES?5APU?5Device@		; `string'
PUBLIC	??_R2apu@@8					; apu::`RTTI Base Class Array'
PUBLIC	??_R2bus_device@@8				; bus_device::`RTTI Base Class Array'
PUBLIC	??_R2device@@8					; device::`RTTI Base Class Array'
PUBLIC	??_R1A@?0A@EA@apu@@8				; apu::`RTTI Base Class Descriptor at (0,-1,0,64)'
PUBLIC	??_R1A@?0A@EA@bus_device@@8			; bus_device::`RTTI Base Class Descriptor at (0,-1,0,64)'
PUBLIC	??_R1A@?0A@EA@device@@8				; device::`RTTI Base Class Descriptor at (0,-1,0,64)'
PUBLIC	??_R3bus_device@@8				; bus_device::`RTTI Class Hierarchy Descriptor'
PUBLIC	??_R0?AVbus_device@@@8				; bus_device `RTTI Type Descriptor'
PUBLIC	??_R3device@@8					; device::`RTTI Class Hierarchy Descriptor'
PUBLIC	??_R0?AVdevice@@@8				; device `RTTI Type Descriptor'
PUBLIC	??_R3apu@@8					; apu::`RTTI Class Hierarchy Descriptor'
PUBLIC	??_R0?AVapu@@@8					; apu `RTTI Type Descriptor'
PUBLIC	??_R4apu@@6B@					; apu::`RTTI Complete Object Locator'
PUBLIC	??_7apu@@6B@					; apu::`vftable'
EXTRN	??_7type_info@@6B@:BYTE				; type_info::`vftable'
EXTRN	__imp_strcpy_s:PROC
EXTRN	??3@YAXPEAX_K@Z:PROC				; operator delete
EXTRN	__imp___std_terminate:PROC
EXTRN	__security_check_cookie:PROC
EXTRN	__imp___CxxFrameHandler3:PROC
CONST	ENDS
;	COMDAT ??_7apu@@6B@
CONST	SEGMENT
??_7apu@@6B@ DQ	FLAT:??_R4apu@@6B@			; apu::`vftable'
	DQ	FLAT:?rundevice@apu@@UEAAHH@Z
	DQ	FLAT:?dma@device@@UEAAXPEAE_N1@Z
	DQ	FLAT:??_Eapu@@UEAAPEAXI@Z
	DQ	FLAT:?write@apu@@UEAAXHHE@Z
	DQ	FLAT:?read@apu@@UEAAEHH@Z
CONST	ENDS
;	COMDAT ??_R4apu@@6B@
rdata$r	SEGMENT
??_R4apu@@6B@ DD 01H					; apu::`RTTI Complete Object Locator'
	DD	00H
	DD	00H
	DD	imagerel ??_R0?AVapu@@@8
	DD	imagerel ??_R3apu@@8
	DD	imagerel ??_R4apu@@6B@
rdata$r	ENDS
;	COMDAT ??_R0?AVapu@@@8
data$r	SEGMENT
??_R0?AVapu@@@8 DQ FLAT:??_7type_info@@6B@		; apu `RTTI Type Descriptor'
	DQ	0000000000000000H
	DB	'.?AVapu@@', 00H
data$r	ENDS
;	COMDAT ??_R3apu@@8
rdata$r	SEGMENT
??_R3apu@@8 DD	00H					; apu::`RTTI Class Hierarchy Descriptor'
	DD	00H
	DD	03H
	DD	imagerel ??_R2apu@@8
rdata$r	ENDS
;	COMDAT ??_R0?AVdevice@@@8
data$r	SEGMENT
??_R0?AVdevice@@@8 DQ FLAT:??_7type_info@@6B@		; device `RTTI Type Descriptor'
	DQ	0000000000000000H
	DB	'.?AVdevice@@', 00H
data$r	ENDS
;	COMDAT ??_R3device@@8
rdata$r	SEGMENT
??_R3device@@8 DD 00H					; device::`RTTI Class Hierarchy Descriptor'
	DD	00H
	DD	01H
	DD	imagerel ??_R2device@@8
rdata$r	ENDS
;	COMDAT ??_R0?AVbus_device@@@8
data$r	SEGMENT
??_R0?AVbus_device@@@8 DQ FLAT:??_7type_info@@6B@	; bus_device `RTTI Type Descriptor'
	DQ	0000000000000000H
	DB	'.?AVbus_device@@', 00H
data$r	ENDS
;	COMDAT ??_R3bus_device@@8
rdata$r	SEGMENT
??_R3bus_device@@8 DD 00H				; bus_device::`RTTI Class Hierarchy Descriptor'
	DD	00H
	DD	02H
	DD	imagerel ??_R2bus_device@@8
rdata$r	ENDS
;	COMDAT ??_R1A@?0A@EA@device@@8
rdata$r	SEGMENT
??_R1A@?0A@EA@device@@8 DD imagerel ??_R0?AVdevice@@@8	; device::`RTTI Base Class Descriptor at (0,-1,0,64)'
	DD	00H
	DD	00H
	DD	0ffffffffH
	DD	00H
	DD	040H
	DD	imagerel ??_R3device@@8
rdata$r	ENDS
;	COMDAT ??_R1A@?0A@EA@bus_device@@8
rdata$r	SEGMENT
??_R1A@?0A@EA@bus_device@@8 DD imagerel ??_R0?AVbus_device@@@8 ; bus_device::`RTTI Base Class Descriptor at (0,-1,0,64)'
	DD	01H
	DD	00H
	DD	0ffffffffH
	DD	00H
	DD	040H
	DD	imagerel ??_R3bus_device@@8
rdata$r	ENDS
;	COMDAT ??_R1A@?0A@EA@apu@@8
rdata$r	SEGMENT
??_R1A@?0A@EA@apu@@8 DD imagerel ??_R0?AVapu@@@8	; apu::`RTTI Base Class Descriptor at (0,-1,0,64)'
	DD	02H
	DD	00H
	DD	0ffffffffH
	DD	00H
	DD	040H
	DD	imagerel ??_R3apu@@8
rdata$r	ENDS
;	COMDAT ??_R2device@@8
rdata$r	SEGMENT
??_R2device@@8 DD imagerel ??_R1A@?0A@EA@device@@8	; device::`RTTI Base Class Array'
	ORG $+3
rdata$r	ENDS
;	COMDAT ??_R2bus_device@@8
rdata$r	SEGMENT
??_R2bus_device@@8 DD imagerel ??_R1A@?0A@EA@bus_device@@8 ; bus_device::`RTTI Base Class Array'
	DD	imagerel ??_R1A@?0A@EA@device@@8
	ORG $+3
rdata$r	ENDS
;	COMDAT ??_R2apu@@8
rdata$r	SEGMENT
??_R2apu@@8 DD	imagerel ??_R1A@?0A@EA@apu@@8		; apu::`RTTI Base Class Array'
	DD	imagerel ??_R1A@?0A@EA@bus_device@@8
	DD	imagerel ??_R1A@?0A@EA@device@@8
	ORG $+3
rdata$r	ENDS
;	COMDAT ??_C@_0P@IDHECIDN@NES?5APU?5Device@
CONST	SEGMENT
??_C@_0P@IDHECIDN@NES?5APU?5Device@ DB 'NES APU Device', 00H ; `string'
CONST	ENDS
PUBLIC	?rundevice@apu@@UEAAHH@Z			; apu::rundevice
PUBLIC	?write@apu@@UEAAXHHE@Z				; apu::write
PUBLIC	?read@apu@@UEAAEHH@Z				; apu::read
PUBLIC	??1apu@@UEAA@XZ					; apu::~apu
PUBLIC	??_Gapu@@UEAAPEAXI@Z				; apu::`scalar deleting destructor'
PUBLIC	??0apu@@QEAA@XZ					; apu::apu
EXTRN	??_Eapu@@UEAAPEAXI@Z:PROC			; apu::`vector deleting destructor'
EXTRN	_CxxThrowException:PROC
EXTRN	__CxxFrameHandler3:PROC
EXTRN	__GSHandlerCheck:PROC
EXTRN	__GSHandlerCheck_EH:PROC
EXTRN	__std_terminate:PROC
EXTRN	memcpy:PROC
EXTRN	memmove:PROC
EXTRN	memset:PROC
EXTRN	__ImageBase:BYTE
EXTRN	__security_cookie:QWORD
;	COMDAT pdata
pdata	SEGMENT
$pdata$??_Gapu@@UEAAPEAXI@Z DD imagerel $LN15@scalar
	DD	imagerel $LN15@scalar+67
	DD	imagerel $unwind$??_Gapu@@UEAAPEAXI@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??0apu@@QEAA@XZ DD imagerel $LN7@apu
	DD	imagerel $LN7@apu+91
	DD	imagerel $unwind$??0apu@@QEAA@XZ
;	COMDAT xdata
xdata	SEGMENT
$unwind$??0apu@@QEAA@XZ DD 020601H
	DD	030023206H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??_Gapu@@UEAAPEAXI@Z DD 040a01H
	DD	06340aH
	DD	07006320aH
xdata	ENDS
END
