; Listing generated by Microsoft (R) Optimizing Compiler Version 19.16.27050.0 

include listing.inc

INCLUDELIB OLDNAMES

PUBLIC	??_C@_01LBDDMOBJ@?$FN@				; `string'
PUBLIC	??_C@_0BE@IJMACPFN@registered?5device?5?$FL@	; `string'
PUBLIC	??_C@_0FA@CLHJNGFJ@?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9@ ; `string'
PUBLIC	??_C@_05BDHPAJIP@?5?9?50x@			; `string'
PUBLIC	??_C@_0BO@KMHDIEBP@device?5operating?5range?5is?5?$FL0x@ ; `string'
PUBLIC	??_C@_0BM@GMLPKDLM@device?5adressing?5mask?5is?50x@ ; `string'
PUBLIC	??_C@_06LCIDCBMH@?5bytes@			; `string'
PUBLIC	??_C@_0BK@HECGDHBI@device?5reports?5size?5is?50x@ ; `string'
PUBLIC	??_C@_03ICICOMAL@yes@				; `string'
PUBLIC	??_C@_02KAJCLHKP@no@				; `string'
PUBLIC	??_C@_0BO@HBKBAGAM@full?5bus?5emulation?5required?$DP?5@ ; `string'
PUBLIC	??_C@_0BH@GDKDGNOP@Denver?5Base?5I?1O?5Device@	; `string'
PUBLIC	??_C@_0BD@MAHCLMLC@Denver?5Base?5Device@	; `string'
PUBLIC	??_C@_0BD@OLBABOEK@vector?$DMT?$DO?5too?5long@	; `string'
PUBLIC	??_R4bus_device@@6B@				; bus_device::`RTTI Complete Object Locator'
PUBLIC	??_R4device@@6B@				; device::`RTTI Complete Object Locator'
PUBLIC	??_7device@@6B@					; device::`vftable'
PUBLIC	??_7bus_device@@6B@				; bus_device::`vftable'
EXTRN	__imp_?rdstate@ios_base@std@@QEBAHXZ:PROC
EXTRN	__imp_?good@ios_base@std@@QEBA_NXZ:PROC
EXTRN	__imp_?flags@ios_base@std@@QEBAHXZ:PROC
EXTRN	__imp_?setf@ios_base@std@@QEAAHHH@Z:PROC
EXTRN	__imp_?width@ios_base@std@@QEBA_JXZ:PROC
EXTRN	__imp_?width@ios_base@std@@QEAA_J_J@Z:PROC
EXTRN	__imp_??6?$basic_ostream@DU?$char_traits@D@std@@@std@@QEAAAEAV01@H@Z:PROC
EXTRN	__imp_??6?$basic_ostream@DU?$char_traits@D@std@@@std@@QEAAAEAV01@P6AAEAVios_base@1@AEAV21@@Z@Z:PROC
EXTRN	__imp_??6?$basic_ostream@DU?$char_traits@D@std@@@std@@QEAAAEAV01@P6AAEAV01@AEAV01@@Z@Z:PROC
EXTRN	__imp_?fill@?$basic_ios@DU?$char_traits@D@std@@@std@@QEBADXZ:PROC
EXTRN	__imp_?rdbuf@?$basic_ios@DU?$char_traits@D@std@@@std@@QEBAPEAV?$basic_streambuf@DU?$char_traits@D@std@@@2@XZ:PROC
EXTRN	__imp_?setstate@?$basic_ios@DU?$char_traits@D@std@@@std@@QEAAXH_N@Z:PROC
EXTRN	__imp_?flush@?$basic_ostream@DU?$char_traits@D@std@@@std@@QEAAAEAV12@XZ:PROC
EXTRN	__imp_?_Osfx@?$basic_ostream@DU?$char_traits@D@std@@@std@@QEAAXXZ:PROC
EXTRN	__imp_?tie@?$basic_ios@DU?$char_traits@D@std@@@std@@QEBAPEAV?$basic_ostream@DU?$char_traits@D@std@@@2@XZ:PROC
EXTRN	__imp_?sputc@?$basic_streambuf@DU?$char_traits@D@std@@@std@@QEAAHD@Z:PROC
EXTRN	__imp_?put@?$basic_ostream@DU?$char_traits@D@std@@@std@@QEAAAEAV12@D@Z:PROC
EXTRN	__imp_?sputn@?$basic_streambuf@DU?$char_traits@D@std@@@std@@QEAA_JPEBD_J@Z:PROC
EXTRN	__imp_?widen@?$basic_ios@DU?$char_traits@D@std@@@std@@QEBADD@Z:PROC
EXTRN	__imp_?_Xlength_error@std@@YAXPEBD@Z:PROC
EXTRN	__imp_?uncaught_exception@std@@YA_NXZ:PROC
EXTRN	__imp_malloc:PROC
EXTRN	__imp_?cout@std@@3V?$basic_ostream@DU?$char_traits@D@std@@@1@A:BYTE
EXTRN	??2@YAPEAX_K@Z:PROC				; operator new
EXTRN	__imp__invalid_parameter_noinfo_noreturn:PROC
EXTRN	__imp_free:PROC
;	COMDAT ??_7bus_device@@6B@
CONST	SEGMENT
??_7bus_device@@6B@ DQ FLAT:??_R4bus_device@@6B@	; bus_device::`vftable'
	DQ	FLAT:?rundevice@device@@UEAAHH@Z
	DQ	FLAT:?dma@device@@UEAAXPEAE_N1@Z
	DQ	FLAT:??_Ebus_device@@UEAAPEAXI@Z
	DQ	FLAT:?write@bus_device@@UEAAXHHE@Z
	DQ	FLAT:?read@bus_device@@UEAAEHH@Z
CONST	ENDS
;	COMDAT ??_7device@@6B@
CONST	SEGMENT
??_7device@@6B@ DQ FLAT:??_R4device@@6B@		; device::`vftable'
	DQ	FLAT:?rundevice@device@@UEAAHH@Z
	DQ	FLAT:?dma@device@@UEAAXPEAE_N1@Z
CONST	ENDS
;	COMDAT ??_R4device@@6B@
rdata$r	SEGMENT
??_R4device@@6B@ DD 01H					; device::`RTTI Complete Object Locator'
	DD	00H
	DD	00H
	DD	imagerel ??_R0?AVdevice@@@8
	DD	imagerel ??_R3device@@8
	DD	imagerel ??_R4device@@6B@
rdata$r	ENDS
;	COMDAT ??_R4bus_device@@6B@
rdata$r	SEGMENT
??_R4bus_device@@6B@ DD 01H				; bus_device::`RTTI Complete Object Locator'
	DD	00H
	DD	00H
	DD	imagerel ??_R0?AVbus_device@@@8
	DD	imagerel ??_R3bus_device@@8
	DD	imagerel ??_R4bus_device@@6B@
rdata$r	ENDS
;	COMDAT ??_C@_0BD@OLBABOEK@vector?$DMT?$DO?5too?5long@
CONST	SEGMENT
??_C@_0BD@OLBABOEK@vector?$DMT?$DO?5too?5long@ DB 'vector<T> too long', 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_0BD@MAHCLMLC@Denver?5Base?5Device@
CONST	SEGMENT
??_C@_0BD@MAHCLMLC@Denver?5Base?5Device@ DB 'Denver Base Device', 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_0BH@GDKDGNOP@Denver?5Base?5I?1O?5Device@
CONST	SEGMENT
??_C@_0BH@GDKDGNOP@Denver?5Base?5I?1O?5Device@ DB 'Denver Base I/O Device'
	DB	00H						; `string'
CONST	ENDS
;	COMDAT ??_C@_0BO@HBKBAGAM@full?5bus?5emulation?5required?$DP?5@
CONST	SEGMENT
??_C@_0BO@HBKBAGAM@full?5bus?5emulation?5required?$DP?5@ DB 'full bus emu'
	DB	'lation required? ', 00H			; `string'
CONST	ENDS
;	COMDAT ??_C@_02KAJCLHKP@no@
CONST	SEGMENT
??_C@_02KAJCLHKP@no@ DB 'no', 00H			; `string'
CONST	ENDS
;	COMDAT ??_C@_03ICICOMAL@yes@
CONST	SEGMENT
??_C@_03ICICOMAL@yes@ DB 'yes', 00H			; `string'
CONST	ENDS
;	COMDAT ??_C@_0BK@HECGDHBI@device?5reports?5size?5is?50x@
CONST	SEGMENT
??_C@_0BK@HECGDHBI@device?5reports?5size?5is?50x@ DB 'device reports size'
	DB	' is 0x', 00H				; `string'
CONST	ENDS
;	COMDAT ??_C@_06LCIDCBMH@?5bytes@
CONST	SEGMENT
??_C@_06LCIDCBMH@?5bytes@ DB ' bytes', 00H		; `string'
CONST	ENDS
;	COMDAT ??_C@_0BM@GMLPKDLM@device?5adressing?5mask?5is?50x@
CONST	SEGMENT
??_C@_0BM@GMLPKDLM@device?5adressing?5mask?5is?50x@ DB 'device adressing '
	DB	'mask is 0x', 00H				; `string'
CONST	ENDS
;	COMDAT ??_C@_0BO@KMHDIEBP@device?5operating?5range?5is?5?$FL0x@
CONST	SEGMENT
??_C@_0BO@KMHDIEBP@device?5operating?5range?5is?5?$FL0x@ DB 'device opera'
	DB	'ting range is [0x', 00H			; `string'
CONST	ENDS
;	COMDAT ??_C@_05BDHPAJIP@?5?9?50x@
CONST	SEGMENT
??_C@_05BDHPAJIP@?5?9?50x@ DB ' - 0x', 00H		; `string'
CONST	ENDS
;	COMDAT ??_C@_0FA@CLHJNGFJ@?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9@
CONST	SEGMENT
??_C@_0FA@CLHJNGFJ@?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9@ DB '-'
	DB	'-------------------------------------------------------------'
	DB	'-----------------', 00H			; `string'
CONST	ENDS
;	COMDAT ??_C@_0BE@IJMACPFN@registered?5device?5?$FL@
CONST	SEGMENT
??_C@_0BE@IJMACPFN@registered?5device?5?$FL@ DB 'registered device [', 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_01LBDDMOBJ@?$FN@
CONST	SEGMENT
??_C@_01LBDDMOBJ@?$FN@ DB ']', 00H			; `string'
PUBLIC	??$_Seek_wrapped@PEAVbus_device@@@std@@YAXAEAPEAPEAVbus_device@@QEAPEAV1@@Z ; std::_Seek_wrapped<bus_device *>
PUBLIC	??$_Uninitialized_move_al_unchecked@PEAVbus_device@@PEAV1@V?$allocator@PEAVbus_device@@@std@@@std@@YAPEAPEAVbus_device@@QEAPEAV1@00AEAV?$allocator@PEAVbus_device@@@0@U_Really_trivial_ptr_iterator_tag@0@U?$integral_constant@_N$00@0@@Z ; std::_Uninitialized_move_al_unchecked<bus_device *,bus_device *,std::allocator<bus_device *> >
PUBLIC	??$_Get_unwrapped_n@PEAVbus_device@@_J$0A@@std@@YAPEAPEAVbus_device@@QEAPEAV1@_J@Z ; std::_Get_unwrapped_n<bus_device *,__int64,0>
PUBLIC	??$_Idl_distance1@PEAPEAVbus_device@@PEAPEAV1@@std@@YA_JAEBQEAPEAVbus_device@@0Urandom_access_iterator_tag@0@@Z ; std::_Idl_distance1<bus_device * *,bus_device * *>
PUBLIC	??$_Get_unwrapped@PEAVbus_device@@@std@@YAPEAPEAVbus_device@@QEAPEAV1@@Z ; std::_Get_unwrapped<bus_device *>
PUBLIC	??$_Copy_memmove@PEAPEAVbus_device@@PEAPEAV1@@std@@YAPEAPEAVbus_device@@PEAPEAV1@00@Z ; std::_Copy_memmove<bus_device * *,bus_device * *>
PUBLIC	??$_Get_size_of_n@$07@std@@YA_K_K@Z		; std::_Get_size_of_n<8>
PUBLIC	??$_Idl_distance@PEAPEAVbus_device@@PEAPEAV1@@std@@YA_JAEBQEAPEAVbus_device@@0@Z ; std::_Idl_distance<bus_device * *,bus_device * *>
PUBLIC	??$_Uninitialized_move@PEAPEAVbus_device@@PEAPEAV1@V?$allocator@PEAVbus_device@@@std@@@std@@YAPEAPEAVbus_device@@QEAPEAV1@0PEAPEAV1@AEAV?$allocator@PEAVbus_device@@@0@@Z ; std::_Uninitialized_move<bus_device * *,bus_device * *,std::allocator<bus_device *> >
PUBLIC	??$_Destroy_range1@V?$allocator@PEAVbus_device@@@std@@@std@@YAXPEAPEAVbus_device@@0AEAV?$allocator@PEAVbus_device@@@0@U?$integral_constant@_N$00@0@@Z ; std::_Destroy_range1<std::allocator<bus_device *> >
PUBLIC	??$_Allocate_manually_vector_aligned@U_Default_allocate_traits@std@@@std@@YAPEAX_K@Z ; std::_Allocate_manually_vector_aligned<std::_Default_allocate_traits>
PUBLIC	??$_Move_unchecked1@PEAPEAVbus_device@@PEAPEAV1@@std@@YAPEAPEAVbus_device@@PEAPEAV1@00U_Trivially_copyable_ptr_iterator_tag@0@@Z ; std::_Move_unchecked1<bus_device * *,bus_device * *>
PUBLIC	??$_Ptr_move_cat@PEAVbus_device@@PEAV1@@std@@YA?AU_Really_trivial_ptr_iterator_tag@0@AEBQEAPEAVbus_device@@0@Z ; std::_Ptr_move_cat<bus_device *,bus_device *>
PUBLIC	?_Get_first@?$_Compressed_pair@V?$allocator@PEAVbus_device@@@std@@V?$_Vector_val@U?$_Simple_types@PEAVbus_device@@@std@@@2@$00@std@@QEBAAEBV?$allocator@PEAVbus_device@@@2@XZ ; std::_Compressed_pair<std::allocator<bus_device *>,std::_Vector_val<std::_Simple_types<bus_device *> >,1>::_Get_first
PUBLIC	?_Umove_if_noexcept1@?$vector@PEAVbus_device@@V?$allocator@PEAVbus_device@@@std@@@std@@AEAAXPEAPEAVbus_device@@00U?$integral_constant@_N$00@2@@Z ; std::vector<bus_device *,std::allocator<bus_device *> >::_Umove_if_noexcept1
PUBLIC	?_Getal@?$_Vector_alloc@U?$_Vec_base_types@PEAVbus_device@@V?$allocator@PEAVbus_device@@@std@@@std@@@std@@QEBAAEBV?$allocator@PEAVbus_device@@@2@XZ ; std::_Vector_alloc<std::_Vec_base_types<bus_device *,std::allocator<bus_device *> > >::_Getal
PUBLIC	?max_size@?$_Default_allocator_traits@V?$allocator@PEAVbus_device@@@std@@@std@@SA_KAEBV?$allocator@PEAVbus_device@@@2@@Z ; std::_Default_allocator_traits<std::allocator<bus_device *> >::max_size
PUBLIC	??0?$allocator@PEAVbus_device@@@std@@QEAA@XZ	; std::allocator<bus_device *>::allocator<bus_device *>
PUBLIC	?allocate@?$allocator@PEAVbus_device@@@std@@QEAAPEAPEAVbus_device@@_K@Z ; std::allocator<bus_device *>::allocate
PUBLIC	?max_size@?$vector@PEAVbus_device@@V?$allocator@PEAVbus_device@@@std@@@std@@QEBA_KXZ ; std::vector<bus_device *,std::allocator<bus_device *> >::max_size
PUBLIC	?_Umove@?$vector@PEAVbus_device@@V?$allocator@PEAVbus_device@@@std@@@std@@AEAAPEAPEAVbus_device@@PEAPEAV3@00@Z ; std::vector<bus_device *,std::allocator<bus_device *> >::_Umove
PUBLIC	?_Umove_if_noexcept@?$vector@PEAVbus_device@@V?$allocator@PEAVbus_device@@@std@@@std@@AEAAXPEAPEAVbus_device@@00@Z ; std::vector<bus_device *,std::allocator<bus_device *> >::_Umove_if_noexcept
PUBLIC	?_Calculate_growth@?$vector@PEAVbus_device@@V?$allocator@PEAVbus_device@@@std@@@std@@AEBA_K_K@Z ; std::vector<bus_device *,std::allocator<bus_device *> >::_Calculate_growth
PUBLIC	?_Change_array@?$vector@PEAVbus_device@@V?$allocator@PEAVbus_device@@@std@@@std@@AEAAXQEAPEAVbus_device@@_K1@Z ; std::vector<bus_device *,std::allocator<bus_device *> >::_Change_array
PUBLIC	?_Xlength@?$vector@PEAVbus_device@@V?$allocator@PEAVbus_device@@@std@@@std@@CAXXZ ; std::vector<bus_device *,std::allocator<bus_device *> >::_Xlength
PUBLIC	??0?$_Vector_val@U?$_Simple_types@PEAVbus_device@@@std@@@std@@QEAA@XZ ; std::_Vector_val<std::_Simple_types<bus_device *> >::_Vector_val<std::_Simple_types<bus_device *> >
PUBLIC	??$_Destroy_range@V?$allocator@PEAVbus_device@@@std@@@std@@YAXPEAPEAVbus_device@@0AEAV?$allocator@PEAVbus_device@@@0@@Z ; std::_Destroy_range<std::allocator<bus_device *> >
PUBLIC	??$_Deallocate@$0BA@$0A@@std@@YAXPEAX_K@Z	; std::_Deallocate<16,0>
PUBLIC	??$_Allocate@$0BA@U_Default_allocate_traits@std@@$0A@@std@@YAPEAX_K@Z ; std::_Allocate<16,std::_Default_allocate_traits,0>
PUBLIC	??$?0$$V@?$_Compressed_pair@V?$allocator@PEAVbus_device@@@std@@V?$_Vector_val@U?$_Simple_types@PEAVbus_device@@@std@@@2@$00@std@@QEAA@U_Zero_then_variadic_args_t@1@@Z ; std::_Compressed_pair<std::allocator<bus_device *>,std::_Vector_val<std::_Simple_types<bus_device *> >,1>::_Compressed_pair<std::allocator<bus_device *>,std::_Vector_val<std::_Simple_types<bus_device *> >,1><>
PUBLIC	??$_Emplace_reallocate@AEBQEAVbus_device@@@?$vector@PEAVbus_device@@V?$allocator@PEAVbus_device@@@std@@@std@@QEAAPEAPEAVbus_device@@QEAPEAV2@AEBQEAV2@@Z ; std::vector<bus_device *,std::allocator<bus_device *> >::_Emplace_reallocate<bus_device * const &>
PUBLIC	??$construct@PEAVbus_device@@AEBQEAV1@@?$_Default_allocator_traits@V?$allocator@PEAVbus_device@@@std@@@std@@SAXAEAV?$allocator@PEAVbus_device@@@1@QEAPEAVbus_device@@AEBQEAV3@@Z ; std::_Default_allocator_traits<std::allocator<bus_device *> >::construct<bus_device *,bus_device * const &>
PUBLIC	??$forward@AEBQEAVbus_device@@@std@@YAAEBQEAVbus_device@@AEBQEAV1@@Z ; std::forward<bus_device * const &>
PUBLIC	??$destroy@PEAVbus_device@@@?$_Default_allocator_traits@V?$allocator@PEAVbus_device@@@std@@@std@@SAXAEAV?$allocator@PEAVbus_device@@@1@QEAPEAVbus_device@@@Z ; std::_Default_allocator_traits<std::allocator<bus_device *> >::destroy<bus_device *>
PUBLIC	??$_Unfancy@PEAVbus_device@@@std@@YAPEAPEAVbus_device@@PEAPEAV1@@Z ; std::_Unfancy<bus_device *>
PUBLIC	??$_Move_unchecked@PEAPEAVbus_device@@PEAPEAV1@@std@@YAPEAPEAVbus_device@@PEAPEAV1@00@Z ; std::_Move_unchecked<bus_device * *,bus_device * *>
PUBLIC	??$addressof@V?$_Vector_val@U?$_Simple_types@PEAVbus_device@@@std@@@std@@@std@@YAPEAV?$_Vector_val@U?$_Simple_types@PEAVbus_device@@@std@@@0@AEAV10@@Z ; std::addressof<std::_Vector_val<std::_Simple_types<bus_device *> > >
PUBLIC	??$endl@DU?$char_traits@D@std@@@std@@YAAEAV?$basic_ostream@DU?$char_traits@D@std@@@0@AEAV10@@Z ; std::endl<char,std::char_traits<char> >
PUBLIC	??$?6U?$char_traits@D@std@@@std@@YAAEAV?$basic_ostream@DU?$char_traits@D@std@@@0@AEAV10@PEBD@Z ; std::operator<<<std::char_traits<char> >
PUBLIC	??$_Min_value@_K@std@@YAAEB_KAEB_K0@Z		; std::_Min_value<unsigned __int64>
PUBLIC	?_Verify_offset@?$_Vector_const_iterator@V?$_Vector_val@U?$_Simple_types@PEAVbus_device@@@std@@@std@@@std@@QEBAX_J@Z ; std::_Vector_const_iterator<std::_Vector_val<std::_Simple_types<bus_device *> > >::_Verify_offset
PUBLIC	?_Get_second@?$_Compressed_pair@V?$allocator@PEAVbus_device@@@std@@V?$_Vector_val@U?$_Simple_types@PEAVbus_device@@@std@@@2@$00@std@@QEBAAEBV?$_Vector_val@U?$_Simple_types@PEAVbus_device@@@std@@@2@XZ ; std::_Compressed_pair<std::allocator<bus_device *>,std::_Vector_val<std::_Simple_types<bus_device *> >,1>::_Get_second
PUBLIC	?deallocate@?$allocator@PEAVbus_device@@@std@@QEAAXQEAPEAVbus_device@@_K@Z ; std::allocator<bus_device *>::deallocate
PUBLIC	?capacity@?$vector@PEAVbus_device@@V?$allocator@PEAVbus_device@@@std@@@std@@QEBA_KXZ ; std::vector<bus_device *,std::allocator<bus_device *> >::capacity
PUBLIC	?_Destroy@?$vector@PEAVbus_device@@V?$allocator@PEAVbus_device@@@std@@@std@@AEAAXPEAPEAVbus_device@@0@Z ; std::vector<bus_device *,std::allocator<bus_device *> >::_Destroy
PUBLIC	?_Orphan_all@?$_Vector_alloc@U?$_Vec_base_types@PEAVbus_device@@V?$allocator@PEAVbus_device@@@std@@@std@@@std@@QEAAXXZ ; std::_Vector_alloc<std::_Vec_base_types<bus_device *,std::allocator<bus_device *> > >::_Orphan_all
PUBLIC	?_Get_data@?$_Vector_alloc@U?$_Vec_base_types@PEAVbus_device@@V?$allocator@PEAVbus_device@@@std@@@std@@@std@@QEBAAEBV?$_Vector_val@U?$_Simple_types@PEAVbus_device@@@std@@@2@XZ ; std::_Vector_alloc<std::_Vec_base_types<bus_device *,std::allocator<bus_device *> > >::_Get_data
PUBLIC	?_Myend@?$_Vector_alloc@U?$_Vec_base_types@PEAVbus_device@@V?$allocator@PEAVbus_device@@@std@@@std@@@std@@QEAAAEAPEAPEAVbus_device@@XZ ; std::_Vector_alloc<std::_Vec_base_types<bus_device *,std::allocator<bus_device *> > >::_Myend
PUBLIC	?_Myend@?$_Vector_alloc@U?$_Vec_base_types@PEAVbus_device@@V?$allocator@PEAVbus_device@@@std@@@std@@@std@@QEBAAEBQEAPEAVbus_device@@XZ ; std::_Vector_alloc<std::_Vec_base_types<bus_device *,std::allocator<bus_device *> > >::_Myend
PUBLIC	??0?$_Vector_const_iterator@V?$_Vector_val@U?$_Simple_types@PEAVbus_device@@@std@@@std@@@std@@QEAA@PEAPEAVbus_device@@PEBU_Container_base0@1@@Z ; std::_Vector_const_iterator<std::_Vector_val<std::_Simple_types<bus_device *> > >::_Vector_const_iterator<std::_Vector_val<std::_Simple_types<bus_device *> > >
PUBLIC	??Y?$_Vector_const_iterator@V?$_Vector_val@U?$_Simple_types@PEAVbus_device@@@std@@@std@@@std@@QEAAAEAV01@_J@Z ; std::_Vector_const_iterator<std::_Vector_val<std::_Simple_types<bus_device *> > >::operator+=
PUBLIC	?_Get_first@?$_Compressed_pair@V?$allocator@PEAVbus_device@@@std@@V?$_Vector_val@U?$_Simple_types@PEAVbus_device@@@std@@@2@$00@std@@QEAAAEAV?$allocator@PEAVbus_device@@@2@XZ ; std::_Compressed_pair<std::allocator<bus_device *>,std::_Vector_val<std::_Simple_types<bus_device *> >,1>::_Get_first
PUBLIC	?_Get_second@?$_Compressed_pair@V?$allocator@PEAVbus_device@@@std@@V?$_Vector_val@U?$_Simple_types@PEAVbus_device@@@std@@@2@$00@std@@QEAAAEAV?$_Vector_val@U?$_Simple_types@PEAVbus_device@@@std@@@2@XZ ; std::_Compressed_pair<std::allocator<bus_device *>,std::_Vector_val<std::_Simple_types<bus_device *> >,1>::_Get_second
PUBLIC	??0_Sentry_base@?$basic_ostream@DU?$char_traits@D@std@@@std@@QEAA@AEAV12@@Z ; std::basic_ostream<char,std::char_traits<char> >::_Sentry_base::_Sentry_base
PUBLIC	??1_Sentry_base@?$basic_ostream@DU?$char_traits@D@std@@@std@@QEAA@XZ ; std::basic_ostream<char,std::char_traits<char> >::_Sentry_base::~_Sentry_base
PUBLIC	?_Has_unused_capacity@?$vector@PEAVbus_device@@V?$allocator@PEAVbus_device@@@std@@@std@@AEBA_NXZ ; std::vector<bus_device *,std::allocator<bus_device *> >::_Has_unused_capacity
PUBLIC	?_Tidy@?$vector@PEAVbus_device@@V?$allocator@PEAVbus_device@@@std@@@std@@AEAAXXZ ; std::vector<bus_device *,std::allocator<bus_device *> >::_Tidy
PUBLIC	?_Orphan_range@?$vector@PEAVbus_device@@V?$allocator@PEAVbus_device@@@std@@@std@@AEBAXPEAPEAVbus_device@@0@Z ; std::vector<bus_device *,std::allocator<bus_device *> >::_Orphan_range
PUBLIC	??0?$_Vector_alloc@U?$_Vec_base_types@PEAVbus_device@@V?$allocator@PEAVbus_device@@@std@@@std@@@std@@QEAA@XZ ; std::_Vector_alloc<std::_Vec_base_types<bus_device *,std::allocator<bus_device *> > >::_Vector_alloc<std::_Vec_base_types<bus_device *,std::allocator<bus_device *> > >
PUBLIC	?_Getal@?$_Vector_alloc@U?$_Vec_base_types@PEAVbus_device@@V?$allocator@PEAVbus_device@@@std@@@std@@@std@@QEAAAEAV?$allocator@PEAVbus_device@@@2@XZ ; std::_Vector_alloc<std::_Vec_base_types<bus_device *,std::allocator<bus_device *> > >::_Getal
PUBLIC	?_Get_data@?$_Vector_alloc@U?$_Vec_base_types@PEAVbus_device@@V?$allocator@PEAVbus_device@@@std@@@std@@@std@@QEAAAEAV?$_Vector_val@U?$_Simple_types@PEAVbus_device@@@std@@@2@XZ ; std::_Vector_alloc<std::_Vec_base_types<bus_device *,std::allocator<bus_device *> > >::_Get_data
PUBLIC	?_Myfirst@?$_Vector_alloc@U?$_Vec_base_types@PEAVbus_device@@V?$allocator@PEAVbus_device@@@std@@@std@@@std@@QEAAAEAPEAPEAVbus_device@@XZ ; std::_Vector_alloc<std::_Vec_base_types<bus_device *,std::allocator<bus_device *> > >::_Myfirst
PUBLIC	?_Myfirst@?$_Vector_alloc@U?$_Vec_base_types@PEAVbus_device@@V?$allocator@PEAVbus_device@@@std@@@std@@@std@@QEBAAEBQEAPEAVbus_device@@XZ ; std::_Vector_alloc<std::_Vec_base_types<bus_device *,std::allocator<bus_device *> > >::_Myfirst
PUBLIC	?_Mylast@?$_Vector_alloc@U?$_Vec_base_types@PEAVbus_device@@V?$allocator@PEAVbus_device@@@std@@@std@@@std@@QEAAAEAPEAPEAVbus_device@@XZ ; std::_Vector_alloc<std::_Vec_base_types<bus_device *,std::allocator<bus_device *> > >::_Mylast
PUBLIC	?_Mylast@?$_Vector_alloc@U?$_Vec_base_types@PEAVbus_device@@V?$allocator@PEAVbus_device@@@std@@@std@@@std@@QEBAAEBQEAPEAVbus_device@@XZ ; std::_Vector_alloc<std::_Vec_base_types<bus_device *,std::allocator<bus_device *> > >::_Mylast
PUBLIC	??0?$_Vector_iterator@V?$_Vector_val@U?$_Simple_types@PEAVbus_device@@@std@@@std@@@std@@QEAA@PEAPEAVbus_device@@PEBU_Container_base0@1@@Z ; std::_Vector_iterator<std::_Vector_val<std::_Simple_types<bus_device *> > >::_Vector_iterator<std::_Vector_val<std::_Simple_types<bus_device *> > >
PUBLIC	??Y?$_Vector_iterator@V?$_Vector_val@U?$_Simple_types@PEAVbus_device@@@std@@@std@@@std@@QEAAAEAV01@_J@Z ; std::_Vector_iterator<std::_Vector_val<std::_Simple_types<bus_device *> > >::operator+=
PUBLIC	??0sentry@?$basic_ostream@DU?$char_traits@D@std@@@std@@QEAA@AEAV12@@Z ; std::basic_ostream<char,std::char_traits<char> >::sentry::sentry
PUBLIC	??1sentry@?$basic_ostream@DU?$char_traits@D@std@@@std@@QEAA@XZ ; std::basic_ostream<char,std::char_traits<char> >::sentry::~sentry
PUBLIC	??Bsentry@?$basic_ostream@DU?$char_traits@D@std@@@std@@QEBA_NXZ ; std::basic_ostream<char,std::char_traits<char> >::sentry::operator bool
PUBLIC	?__autoclassinit2@?$_Vector_iterator@V?$_Vector_val@U?$_Simple_types@PEAVbus_device@@@std@@@std@@@std@@QEAAX_K@Z ; std::_Vector_iterator<std::_Vector_val<std::_Simple_types<bus_device *> > >::__autoclassinit2
PUBLIC	??0?$vector@PEAVbus_device@@V?$allocator@PEAVbus_device@@@std@@@std@@QEAA@XZ ; std::vector<bus_device *,std::allocator<bus_device *> >::vector<bus_device *,std::allocator<bus_device *> >
PUBLIC	??1?$vector@PEAVbus_device@@V?$allocator@PEAVbus_device@@@std@@@std@@QEAA@XZ ; std::vector<bus_device *,std::allocator<bus_device *> >::~vector<bus_device *,std::allocator<bus_device *> >
PUBLIC	??$_Emplace_back_with_unused_capacity@AEBQEAVbus_device@@@?$vector@PEAVbus_device@@V?$allocator@PEAVbus_device@@@std@@@std@@AEAAXAEBQEAVbus_device@@@Z ; std::vector<bus_device *,std::allocator<bus_device *> >::_Emplace_back_with_unused_capacity<bus_device * const &>
PUBLIC	??$emplace_back@AEBQEAVbus_device@@@?$vector@PEAVbus_device@@V?$allocator@PEAVbus_device@@@std@@@std@@QEAAXAEBQEAVbus_device@@@Z ; std::vector<bus_device *,std::allocator<bus_device *> >::emplace_back<bus_device * const &>
PUBLIC	?push_back@?$vector@PEAVbus_device@@V?$allocator@PEAVbus_device@@@std@@@std@@QEAAXAEBQEAVbus_device@@@Z ; std::vector<bus_device *,std::allocator<bus_device *> >::push_back
PUBLIC	?erase@?$vector@PEAVbus_device@@V?$allocator@PEAVbus_device@@@std@@@std@@QEAA?AV?$_Vector_iterator@V?$_Vector_val@U?$_Simple_types@PEAVbus_device@@@std@@@std@@@2@V?$_Vector_const_iterator@V?$_Vector_val@U?$_Simple_types@PEAVbus_device@@@std@@@std@@@2@@Z ; std::vector<bus_device *,std::allocator<bus_device *> >::erase
PUBLIC	?begin@?$vector@PEAVbus_device@@V?$allocator@PEAVbus_device@@@std@@@std@@QEAA?AV?$_Vector_iterator@V?$_Vector_val@U?$_Simple_types@PEAVbus_device@@@std@@@std@@@2@XZ ; std::vector<bus_device *,std::allocator<bus_device *> >::begin
PUBLIC	?_Unchecked_begin@?$vector@PEAVbus_device@@V?$allocator@PEAVbus_device@@@std@@@std@@QEAAPEAPEAVbus_device@@XZ ; std::vector<bus_device *,std::allocator<bus_device *> >::_Unchecked_begin
PUBLIC	?_Unchecked_end@?$vector@PEAVbus_device@@V?$allocator@PEAVbus_device@@@std@@@std@@QEAAPEAPEAVbus_device@@XZ ; std::vector<bus_device *,std::allocator<bus_device *> >::_Unchecked_end
PUBLIC	?size@?$vector@PEAVbus_device@@V?$allocator@PEAVbus_device@@@std@@@std@@QEBA_KXZ ; std::vector<bus_device *,std::allocator<bus_device *> >::size
PUBLIC	??A?$vector@PEAVbus_device@@V?$allocator@PEAVbus_device@@@std@@@std@@QEAAAEAPEAVbus_device@@_K@Z ; std::vector<bus_device *,std::allocator<bus_device *> >::operator[]
PUBLIC	??H?$_Vector_iterator@V?$_Vector_val@U?$_Simple_types@PEAVbus_device@@@std@@@std@@@std@@QEBA?AV01@_J@Z ; std::_Vector_iterator<std::_Vector_val<std::_Simple_types<bus_device *> > >::operator+
PUBLIC	?rundevice@device@@UEAAHH@Z			; device::rundevice
PUBLIC	??1device@@QEAA@XZ				; device::~device
PUBLIC	??0device@@QEAA@XZ				; device::device
PUBLIC	?read@bus_device@@UEAAEHH@Z			; bus_device::read
PUBLIC	?write@bus_device@@UEAAXHHE@Z			; bus_device::write
PUBLIC	?resetpins_to_default@bus_device@@QEAAXXZ	; bus_device::resetpins_to_default
PUBLIC	?swappins@bus_device@@QEAAXHH@Z			; bus_device::swappins
PUBLIC	?groundpin@bus_device@@QEAAXH@Z			; bus_device::groundpin
PUBLIC	?compute_addr_from_layout@bus_device@@QEAAGG@Z	; bus_device::compute_addr_from_layout
PUBLIC	??_Gbus_device@@UEAAPEAXI@Z			; bus_device::`scalar deleting destructor'
PUBLIC	?reportdevices@bus@@QEAAXXZ			; bus::reportdevices
PUBLIC	?irq_pulled@bus@@QEAA_NXZ			; bus::irq_pulled
PUBLIC	?nmi_pulled@bus@@QEAA_NXZ			; bus::nmi_pulled
PUBLIC	?removedevice_select_base@bus@@QEAAXH@Z		; bus::removedevice_select_base
PUBLIC	?registerdevice@bus@@QEAAXPEAVbus_device@@@Z	; bus::registerdevice
PUBLIC	?read@bus@@QEAAEXZ				; bus::read
PUBLIC	?write@bus@@QEAAXE@Z				; bus::write
PUBLIC	?readmemory_as_word_wrap@bus@@QEAAGH@Z		; bus::readmemory_as_word_wrap
PUBLIC	?readmemory_as_word@bus@@QEAAGH@Z		; bus::readmemory_as_word
PUBLIC	?readmemory@bus@@QEAAEH@Z			; bus::readmemory
PUBLIC	?writememory@bus@@QEAAXHE@Z			; bus::writememory
PUBLIC	??1bus@@QEAA@XZ					; bus::~bus
PUBLIC	??0bus@@QEAA@XZ					; bus::bus
PUBLIC	?hex@std@@YAAEAVios_base@1@AEAV21@@Z		; std::hex
PUBLIC	?_Adjust_manually_vector_aligned@std@@YAXAEAPEAXAEA_K@Z ; std::_Adjust_manually_vector_aligned
PUBLIC	?_Allocate@_Default_allocate_traits@std@@SAPEAX_K@Z ; std::_Default_allocate_traits::_Allocate
PUBLIC	?_Adopt@_Iterator_base0@std@@QEAAXPEBX@Z	; std::_Iterator_base0::_Adopt
PUBLIC	?_Orphan_all@_Container_base0@std@@QEAAXXZ	; std::_Container_base0::_Orphan_all
PUBLIC	?eof@?$char_traits@D@std@@SAHXZ			; std::char_traits<char>::eof
PUBLIC	?eq_int_type@?$char_traits@D@std@@SA_NAEBH0@Z	; std::char_traits<char>::eq_int_type
PUBLIC	?length@?$char_traits@D@std@@SA_KQEBD@Z		; std::char_traits<char>::length
PUBLIC	?max@?$numeric_limits@_J@std@@SA_JXZ		; std::numeric_limits<__int64>::max
PUBLIC	??2@YAPEAX_KPEAX@Z				; operator new
PUBLIC	??0bus_device@@QEAA@XZ				; bus_device::bus_device
PUBLIC	??1bus_device@@UEAA@XZ				; bus_device::~bus_device
PUBLIC	?get_device_descriptor@device@@QEAAPEADXZ	; device::get_device_descriptor
PUBLIC	?dma@device@@UEAAXPEAE_N1@Z			; device::dma
EXTRN	??_Ebus_device@@UEAAPEAXI@Z:PROC		; bus_device::`vector deleting destructor'
;	COMDAT pdata
pdata	SEGMENT
$pdata$??$_Uninitialized_move_al_unchecked@PEAVbus_device@@PEAV1@V?$allocator@PEAVbus_device@@@std@@@std@@YAPEAPEAVbus_device@@QEAPEAV1@00AEAV?$allocator@PEAVbus_device@@@0@U_Really_trivial_ptr_iterator_tag@0@U?$integral_constant@_N$00@0@@Z DD imagerel $LN6@Uninitiali
	DD	imagerel $LN6@Uninitiali+48
	DD	imagerel $unwind$??$_Uninitialized_move_al_unchecked@PEAVbus_device@@PEAV1@V?$allocator@PEAVbus_device@@@std@@@std@@YAPEAPEAVbus_device@@QEAPEAV1@00AEAV?$allocator@PEAVbus_device@@@0@U_Really_trivial_ptr_iterator_tag@0@U?$integral_constant@_N$00@0@@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??$_Copy_memmove@PEAPEAVbus_device@@PEAPEAV1@@std@@YAPEAPEAVbus_device@@PEAPEAV1@00@Z DD imagerel $LN4@Copy_memmo
	DD	imagerel $LN4@Copy_memmo+48
	DD	imagerel $unwind$??$_Copy_memmove@PEAPEAVbus_device@@PEAPEAV1@@std@@YAPEAPEAVbus_device@@PEAPEAV1@00@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??$_Uninitialized_move@PEAPEAVbus_device@@PEAPEAV1@V?$allocator@PEAVbus_device@@@std@@@std@@YAPEAPEAVbus_device@@QEAPEAV1@0PEAPEAV1@AEAV?$allocator@PEAVbus_device@@@0@@Z DD imagerel $LN22@Uninitiali
	DD	imagerel $LN22@Uninitiali+48
	DD	imagerel $unwind$??$_Uninitialized_move@PEAPEAVbus_device@@PEAPEAV1@V?$allocator@PEAVbus_device@@@std@@@std@@YAPEAPEAVbus_device@@QEAPEAV1@0PEAPEAV1@AEAV?$allocator@PEAVbus_device@@@0@@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??$_Allocate_manually_vector_aligned@U_Default_allocate_traits@std@@@std@@YAPEAX_K@Z DD imagerel $LN16@Allocate_m
	DD	imagerel $LN16@Allocate_m+62
	DD	imagerel $unwind$??$_Allocate_manually_vector_aligned@U_Default_allocate_traits@std@@@std@@YAPEAX_K@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??$_Move_unchecked1@PEAPEAVbus_device@@PEAPEAV1@@std@@YAPEAPEAVbus_device@@PEAPEAV1@00U_Trivially_copyable_ptr_iterator_tag@0@@Z DD imagerel $LN6@Move_unche
	DD	imagerel $LN6@Move_unche+48
	DD	imagerel $unwind$??$_Move_unchecked1@PEAPEAVbus_device@@PEAPEAV1@@std@@YAPEAPEAVbus_device@@PEAPEAV1@00U_Trivially_copyable_ptr_iterator_tag@0@@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?allocate@?$allocator@PEAVbus_device@@@std@@QEAAPEAPEAVbus_device@@_K@Z DD imagerel $LN30@allocate
	DD	imagerel $LN30@allocate+117
	DD	imagerel $unwind$?allocate@?$allocator@PEAVbus_device@@@std@@QEAAPEAPEAVbus_device@@_K@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?_Umove@?$vector@PEAVbus_device@@V?$allocator@PEAVbus_device@@@std@@@std@@AEAAPEAPEAVbus_device@@PEAPEAV3@00@Z DD imagerel $LN29@Umove
	DD	imagerel $LN29@Umove+45
	DD	imagerel $unwind$?_Umove@?$vector@PEAVbus_device@@V?$allocator@PEAVbus_device@@@std@@@std@@AEAAPEAPEAVbus_device@@PEAPEAV3@00@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?_Umove_if_noexcept@?$vector@PEAVbus_device@@V?$allocator@PEAVbus_device@@@std@@@std@@AEAAXPEAPEAVbus_device@@00@Z DD imagerel $LN31@Umove_if_n
	DD	imagerel $LN31@Umove_if_n+48
	DD	imagerel $unwind$?_Umove_if_noexcept@?$vector@PEAVbus_device@@V?$allocator@PEAVbus_device@@@std@@@std@@AEAAXPEAPEAVbus_device@@00@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?_Change_array@?$vector@PEAVbus_device@@V?$allocator@PEAVbus_device@@@std@@@std@@AEAAXQEAPEAVbus_device@@_K1@Z DD imagerel $LN103@Change_arr
	DD	imagerel $LN103@Change_arr+136
	DD	imagerel $unwind$?_Change_array@?$vector@PEAVbus_device@@V?$allocator@PEAVbus_device@@@std@@@std@@AEAAXQEAPEAVbus_device@@_K1@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?_Xlength@?$vector@PEAVbus_device@@V?$allocator@PEAVbus_device@@@std@@@std@@CAXXZ DD imagerel $LN4@Xlength
	DD	imagerel $LN4@Xlength+18
	DD	imagerel $unwind$?_Xlength@?$vector@PEAVbus_device@@V?$allocator@PEAVbus_device@@@std@@@std@@CAXXZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??$_Deallocate@$0BA@$0A@@std@@YAXPEAX_K@Z DD imagerel $LN17@Deallocate
	DD	imagerel $LN17@Deallocate+53
	DD	imagerel $unwind$??$_Deallocate@$0BA@$0A@@std@@YAXPEAX_K@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??$_Allocate@$0BA@U_Default_allocate_traits@std@@$0A@@std@@YAPEAX_K@Z DD imagerel $LN23@Allocate
	DD	imagerel $LN23@Allocate+90
	DD	imagerel $unwind$??$_Allocate@$0BA@U_Default_allocate_traits@std@@$0A@@std@@YAPEAX_K@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??$_Emplace_reallocate@AEBQEAVbus_device@@@?$vector@PEAVbus_device@@V?$allocator@PEAVbus_device@@@std@@@std@@QEAAPEAPEAVbus_device@@QEAPEAV2@AEBQEAV2@@Z DD imagerel $LN338@Emplace_re
	DD	imagerel $LN338@Emplace_re+70
	DD	imagerel $unwind$??$_Emplace_reallocate@AEBQEAVbus_device@@@?$vector@PEAVbus_device@@V?$allocator@PEAVbus_device@@@std@@@std@@QEAAPEAPEAVbus_device@@QEAPEAV2@AEBQEAV2@@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$2$??$_Emplace_reallocate@AEBQEAVbus_device@@@?$vector@PEAVbus_device@@V?$allocator@PEAVbus_device@@@std@@@std@@QEAAPEAPEAVbus_device@@QEAPEAV2@AEBQEAV2@@Z DD imagerel $LN338@Emplace_re+70
	DD	imagerel $LN338@Emplace_re+393
	DD	imagerel $chain$2$??$_Emplace_reallocate@AEBQEAVbus_device@@@?$vector@PEAVbus_device@@V?$allocator@PEAVbus_device@@@std@@@std@@QEAAPEAPEAVbus_device@@QEAPEAV2@AEBQEAV2@@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$4$??$_Emplace_reallocate@AEBQEAVbus_device@@@?$vector@PEAVbus_device@@V?$allocator@PEAVbus_device@@@std@@@std@@QEAAPEAPEAVbus_device@@QEAPEAV2@AEBQEAV2@@Z DD imagerel $LN338@Emplace_re+393
	DD	imagerel $LN338@Emplace_re+400
	DD	imagerel $chain$4$??$_Emplace_reallocate@AEBQEAVbus_device@@@?$vector@PEAVbus_device@@V?$allocator@PEAVbus_device@@@std@@@std@@QEAAPEAPEAVbus_device@@QEAPEAV2@AEBQEAV2@@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$5$??$_Emplace_reallocate@AEBQEAVbus_device@@@?$vector@PEAVbus_device@@V?$allocator@PEAVbus_device@@@std@@@std@@QEAAPEAPEAVbus_device@@QEAPEAV2@AEBQEAV2@@Z DD imagerel $LN338@Emplace_re+400
	DD	imagerel $LN338@Emplace_re+406
	DD	imagerel $chain$5$??$_Emplace_reallocate@AEBQEAVbus_device@@@?$vector@PEAVbus_device@@V?$allocator@PEAVbus_device@@@std@@@std@@QEAAPEAPEAVbus_device@@QEAPEAV2@AEBQEAV2@@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??$_Move_unchecked@PEAPEAVbus_device@@PEAPEAV1@@std@@YAPEAPEAVbus_device@@PEAPEAV1@00@Z DD imagerel $LN10@Move_unche
	DD	imagerel $LN10@Move_unche+48
	DD	imagerel $unwind$??$_Move_unchecked@PEAPEAVbus_device@@PEAPEAV1@@std@@YAPEAPEAVbus_device@@PEAPEAV1@00@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??$endl@DU?$char_traits@D@std@@@std@@YAAEAV?$basic_ostream@DU?$char_traits@D@std@@@0@AEAV10@@Z DD imagerel $LN4@endl
	DD	imagerel $LN4@endl+57
	DD	imagerel $unwind$??$endl@DU?$char_traits@D@std@@@std@@YAAEAV?$basic_ostream@DU?$char_traits@D@std@@@0@AEAV10@@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??$?6U?$char_traits@D@std@@@std@@YAAEAV?$basic_ostream@DU?$char_traits@D@std@@@0@AEAV10@PEBD@Z DD imagerel $LN109@operator
	DD	imagerel $LN109@operator+464
	DD	imagerel $unwind$??$?6U?$char_traits@D@std@@@std@@YAAEAV?$basic_ostream@DU?$char_traits@D@std@@@0@AEAV10@PEBD@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?catch$4@?0???$?6U?$char_traits@D@std@@@std@@YAAEAV?$basic_ostream@DU?$char_traits@D@std@@@0@AEAV10@PEBD@Z@4HA DD imagerel ?catch$4@?0???$?6U?$char_traits@D@std@@@std@@YAAEAV?$basic_ostream@DU?$char_traits@D@std@@@0@AEAV10@PEBD@Z@4HA
	DD	imagerel ?catch$4@?0???$?6U?$char_traits@D@std@@@std@@YAAEAV?$basic_ostream@DU?$char_traits@D@std@@@0@AEAV10@PEBD@Z@4HA+56
	DD	imagerel $unwind$?catch$4@?0???$?6U?$char_traits@D@std@@@std@@YAAEAV?$basic_ostream@DU?$char_traits@D@std@@@0@AEAV10@PEBD@Z@4HA
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?deallocate@?$allocator@PEAVbus_device@@@std@@QEAAXQEAPEAVbus_device@@_K@Z DD imagerel $LN20@deallocate
	DD	imagerel $LN20@deallocate+67
	DD	imagerel $unwind$?deallocate@?$allocator@PEAVbus_device@@@std@@QEAAXQEAPEAVbus_device@@_K@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??0_Sentry_base@?$basic_ostream@DU?$char_traits@D@std@@@std@@QEAA@AEAV12@@Z DD imagerel $LN10@Sentry_bas
	DD	imagerel $LN10@Sentry_bas+44
	DD	imagerel $unwind$??0_Sentry_base@?$basic_ostream@DU?$char_traits@D@std@@@std@@QEAA@AEAV12@@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??1_Sentry_base@?$basic_ostream@DU?$char_traits@D@std@@@std@@QEAA@XZ DD imagerel $LN10@Sentry_bas
	DD	imagerel $LN10@Sentry_bas+45
	DD	imagerel $unwind$??1_Sentry_base@?$basic_ostream@DU?$char_traits@D@std@@@std@@QEAA@XZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?_Tidy@?$vector@PEAVbus_device@@V?$allocator@PEAVbus_device@@@std@@@std@@AEAAXXZ DD imagerel $LN103@Tidy
	DD	imagerel $LN103@Tidy+92
	DD	imagerel $unwind$?_Tidy@?$vector@PEAVbus_device@@V?$allocator@PEAVbus_device@@@std@@@std@@AEAAXXZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??0sentry@?$basic_ostream@DU?$char_traits@D@std@@@std@@QEAA@AEAV12@@Z DD imagerel $LN28@sentry
	DD	imagerel $LN28@sentry+126
	DD	imagerel $unwind$??0sentry@?$basic_ostream@DU?$char_traits@D@std@@@std@@QEAA@AEAV12@@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??1sentry@?$basic_ostream@DU?$char_traits@D@std@@@std@@QEAA@XZ DD imagerel $LN15@sentry
	DD	imagerel $LN15@sentry+72
	DD	imagerel $unwind$??1sentry@?$basic_ostream@DU?$char_traits@D@std@@@std@@QEAA@XZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??1?$vector@PEAVbus_device@@V?$allocator@PEAVbus_device@@@std@@@std@@QEAA@XZ DD imagerel $LN106@vector
	DD	imagerel $LN106@vector+92
	DD	imagerel $unwind$??1?$vector@PEAVbus_device@@V?$allocator@PEAVbus_device@@@std@@@std@@QEAA@XZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?erase@?$vector@PEAVbus_device@@V?$allocator@PEAVbus_device@@@std@@@std@@QEAA?AV?$_Vector_iterator@V?$_Vector_val@U?$_Simple_types@PEAVbus_device@@@std@@@std@@@2@V?$_Vector_const_iterator@V?$_Vector_val@U?$_Simple_types@PEAVbus_device@@@std@@@std@@@2@@Z DD imagerel $LN51@erase
	DD	imagerel $LN51@erase+70
	DD	imagerel $unwind$?erase@?$vector@PEAVbus_device@@V?$allocator@PEAVbus_device@@@std@@@std@@QEAA?AV?$_Vector_iterator@V?$_Vector_val@U?$_Simple_types@PEAVbus_device@@@std@@@std@@@2@V?$_Vector_const_iterator@V?$_Vector_val@U?$_Simple_types@PEAVbus_device@@@std@@@std@@@2@@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??0device@@QEAA@XZ DD imagerel $LN4@device
	DD	imagerel $LN4@device+70
	DD	imagerel $unwind$??0device@@QEAA@XZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?compute_addr_from_layout@bus_device@@QEAAGG@Z DD imagerel $LN16@compute_ad
	DD	imagerel $LN16@compute_ad+123
	DD	imagerel $unwind$?compute_addr_from_layout@bus_device@@QEAAGG@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??_Gbus_device@@UEAAPEAXI@Z DD imagerel $LN12@scalar
	DD	imagerel $LN12@scalar+67
	DD	imagerel $unwind$??_Gbus_device@@UEAAPEAXI@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?reportdevices@bus@@QEAAXXZ DD imagerel $LN30@reportdevi
	DD	imagerel $LN30@reportdevi+47
	DD	imagerel $unwind$?reportdevices@bus@@QEAAXXZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$2$?reportdevices@bus@@QEAAXXZ DD imagerel $LN30@reportdevi+47
	DD	imagerel $LN30@reportdevi+499
	DD	imagerel $chain$2$?reportdevices@bus@@QEAAXXZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$3$?reportdevices@bus@@QEAAXXZ DD imagerel $LN30@reportdevi+499
	DD	imagerel $LN30@reportdevi+508
	DD	imagerel $chain$3$?reportdevices@bus@@QEAAXXZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?removedevice_select_base@bus@@QEAAXH@Z DD imagerel $LN114@removedevi
	DD	imagerel $LN114@removedevi+87
	DD	imagerel $unwind$?removedevice_select_base@bus@@QEAAXH@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?registerdevice@bus@@QEAAXPEAVbus_device@@@Z DD imagerel $LN82@registerde
	DD	imagerel $LN82@registerde+54
	DD	imagerel $unwind$?registerdevice@bus@@QEAAXPEAVbus_device@@@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?read@bus@@QEAAEXZ DD imagerel $LN51@read
	DD	imagerel $LN51@read+37
	DD	imagerel $unwind$?read@bus@@QEAAEXZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$2$?read@bus@@QEAAEXZ DD imagerel $LN51@read+37
	DD	imagerel $LN51@read+258
	DD	imagerel $chain$2$?read@bus@@QEAAEXZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$3$?read@bus@@QEAAEXZ DD imagerel $LN51@read+258
	DD	imagerel $LN51@read+277
	DD	imagerel $chain$3$?read@bus@@QEAAEXZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?write@bus@@QEAAXE@Z DD imagerel $LN49@write
	DD	imagerel $LN49@write+38
	DD	imagerel $unwind$?write@bus@@QEAAXE@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$2$?write@bus@@QEAAXE@Z DD imagerel $LN49@write+38
	DD	imagerel $LN49@write+240
	DD	imagerel $chain$2$?write@bus@@QEAAXE@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$3$?write@bus@@QEAAXE@Z DD imagerel $LN49@write+240
	DD	imagerel $LN49@write+255
	DD	imagerel $chain$3$?write@bus@@QEAAXE@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?readmemory_as_word_wrap@bus@@QEAAGH@Z DD imagerel $LN4@readmemory
	DD	imagerel $LN4@readmemory+83
	DD	imagerel $unwind$?readmemory_as_word_wrap@bus@@QEAAGH@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?readmemory_as_word@bus@@QEAAGH@Z DD imagerel $LN4@readmemory
	DD	imagerel $LN4@readmemory+54
	DD	imagerel $unwind$?readmemory_as_word@bus@@QEAAGH@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?writememory@bus@@QEAAXHE@Z DD imagerel $LN51@writememor
	DD	imagerel $LN51@writememor+40
	DD	imagerel $unwind$?writememory@bus@@QEAAXHE@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$2$?writememory@bus@@QEAAXHE@Z DD imagerel $LN51@writememor+40
	DD	imagerel $LN51@writememor+240
	DD	imagerel $chain$2$?writememory@bus@@QEAAXHE@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$3$?writememory@bus@@QEAAXHE@Z DD imagerel $LN51@writememor+240
	DD	imagerel $LN51@writememor+255
	DD	imagerel $chain$3$?writememory@bus@@QEAAXHE@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??1bus@@QEAA@XZ DD imagerel $LN134@bus
	DD	imagerel $LN134@bus+191
	DD	imagerel $unwind$??1bus@@QEAA@XZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?_Adjust_manually_vector_aligned@std@@YAXAEAPEAXAEA_K@Z DD imagerel $LN13@Adjust_man
	DD	imagerel $LN13@Adjust_man+43
	DD	imagerel $unwind$?_Adjust_manually_vector_aligned@std@@YAXAEAPEAXAEA_K@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??0bus_device@@QEAA@XZ DD imagerel $LN16@bus_device
	DD	imagerel $LN16@bus_device+155
	DD	imagerel $unwind$??0bus_device@@QEAA@XZ
;	COMDAT xdata
xdata	SEGMENT
$unwind$??0bus_device@@QEAA@XZ DD 040a01H
	DD	06340aH
	DD	07006320aH
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?_Adjust_manually_vector_aligned@std@@YAXAEAPEAXAEA_K@Z DD 010401H
	DD	04204H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??1bus@@QEAA@XZ DD 081201H
	DD	0a5412H
	DD	093412H
	DD	0e00e3212H
	DD	0600b700cH
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$chain$3$?writememory@bus@@QEAAXHE@Z DD 021H
	DD	imagerel $LN51@writememor
	DD	imagerel $LN51@writememor+40
	DD	imagerel $unwind$?writememory@bus@@QEAAXHE@Z
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$chain$2$?writememory@bus@@QEAAXHE@Z DD 060f21H
	DD	0ac40fH
	DD	09640aH
	DD	083405H
	DD	imagerel $LN51@writememor
	DD	imagerel $LN51@writememor+40
	DD	imagerel $unwind$?writememory@bus@@QEAAXHE@Z
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?writememory@bus@@QEAAXHE@Z DD 060e01H
	DD	0b540eH
	DD	0f00a320eH
	DD	07006e008H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?readmemory_as_word@bus@@QEAAGH@Z DD 040a01H
	DD	06340aH
	DD	07006320aH
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?readmemory_as_word_wrap@bus@@QEAAGH@Z DD 060f01H
	DD	07640fH
	DD	06340fH
	DD	0700b320fH
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$chain$3$?write@bus@@QEAAXE@Z DD 021H
	DD	imagerel $LN49@write
	DD	imagerel $LN49@write+38
	DD	imagerel $unwind$?write@bus@@QEAAXE@Z
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$chain$2$?write@bus@@QEAAXE@Z DD 060f21H
	DD	0ac40fH
	DD	09640aH
	DD	083405H
	DD	imagerel $LN49@write
	DD	imagerel $LN49@write+38
	DD	imagerel $unwind$?write@bus@@QEAAXE@Z
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?write@bus@@QEAAXE@Z DD 060e01H
	DD	0b540eH
	DD	0f00a320eH
	DD	07006e008H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$chain$3$?read@bus@@QEAAEXZ DD 021H
	DD	imagerel $LN51@read
	DD	imagerel $LN51@read+37
	DD	imagerel $unwind$?read@bus@@QEAAEXZ
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$chain$2$?read@bus@@QEAAEXZ DD 060f21H
	DD	0ac40fH
	DD	09640aH
	DD	083405H
	DD	imagerel $LN51@read
	DD	imagerel $LN51@read+37
	DD	imagerel $unwind$?read@bus@@QEAAEXZ
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?read@bus@@QEAAEXZ DD 060e01H
	DD	0b540eH
	DD	0f00a320eH
	DD	07006e008H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?registerdevice@bus@@QEAAXPEAVbus_device@@@Z DD 010901H
	DD	04209H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?removedevice_select_base@bus@@QEAAXH@Z DD 020601H
	DD	030023206H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$chain$3$?reportdevices@bus@@QEAAXXZ DD 021H
	DD	imagerel $LN30@reportdevi
	DD	imagerel $LN30@reportdevi+47
	DD	imagerel $unwind$?reportdevices@bus@@QEAAXXZ
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$chain$2$?reportdevices@bus@@QEAAXXZ DD 060f21H
	DD	0af40fH
	DD	09740aH
	DD	086405H
	DD	imagerel $LN30@reportdevi
	DD	imagerel $LN30@reportdevi+47
	DD	imagerel $unwind$?reportdevices@bus@@QEAAXXZ
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?reportdevices@bus@@QEAAXXZ DD 040901H
	DD	0e0053209H
	DD	030025003H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??_Gbus_device@@UEAAPEAXI@Z DD 040a01H
	DD	06340aH
	DD	07006320aH
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?compute_addr_from_layout@bus_device@@QEAAGG@Z DD 020501H
	DD	013405H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??0device@@QEAA@XZ DD 020601H
	DD	030023206H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?erase@?$vector@PEAVbus_device@@V?$allocator@PEAVbus_device@@@std@@@std@@QEAA?AV?$_Vector_iterator@V?$_Vector_val@U?$_Simple_types@PEAVbus_device@@@std@@@std@@@2@V?$_Vector_const_iterator@V?$_Vector_val@U?$_Simple_types@PEAVbus_device@@@std@@@std@@@2@@Z DD 060f01H
	DD	09640fH
	DD	08340fH
	DD	0700b320fH
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??1?$vector@PEAVbus_device@@V?$allocator@PEAVbus_device@@@std@@@std@@QEAA@XZ DD 020601H
	DD	030023206H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$ip2state$??1sentry@?$basic_ostream@DU?$char_traits@D@std@@@std@@QEAA@XZ DD imagerel ??1sentry@?$basic_ostream@DU?$char_traits@D@std@@@std@@QEAA@XZ+32
	DD	0ffffffffH
	DD	imagerel ??1sentry@?$basic_ostream@DU?$char_traits@D@std@@@std@@QEAA@XZ+62
	DD	00H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$stateUnwindMap$??1sentry@?$basic_ostream@DU?$char_traits@D@std@@@std@@QEAA@XZ DD 0ffffffffH
	DD	imagerel __std_terminate
xdata	ENDS
;	COMDAT CONST
CONST	SEGMENT
$cppxdata$??1sentry@?$basic_ostream@DU?$char_traits@D@std@@@std@@QEAA@XZ DQ 00000000119930522r ; 2.33398e-314
	DD	imagerel $stateUnwindMap$??1sentry@?$basic_ostream@DU?$char_traits@D@std@@@std@@QEAA@XZ
	DQ	00000000000000000r		; 0
	DD	02H
	DD	imagerel $ip2state$??1sentry@?$basic_ostream@DU?$char_traits@D@std@@@std@@QEAA@XZ
	DQ	00000000000000020r		; 1.58101e-322
	DD	05H
CONST	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??1sentry@?$basic_ostream@DU?$char_traits@D@std@@@std@@QEAA@XZ DD 020f19H
	DD	030025206H
	DD	imagerel __CxxFrameHandler3
	DD	imagerel $cppxdata$??1sentry@?$basic_ostream@DU?$char_traits@D@std@@@std@@QEAA@XZ
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$ip2state$??0sentry@?$basic_ostream@DU?$char_traits@D@std@@@std@@QEAA@AEAV12@@Z DD imagerel ??0sentry@?$basic_ostream@DU?$char_traits@D@std@@@std@@QEAA@AEAV12@@Z+53
	DD	0ffffffffH
	DD	imagerel ??0sentry@?$basic_ostream@DU?$char_traits@D@std@@@std@@QEAA@AEAV12@@Z+88
	DD	00H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$stateUnwindMap$??0sentry@?$basic_ostream@DU?$char_traits@D@std@@@std@@QEAA@AEAV12@@Z DD 0ffffffffH
	DD	imagerel ?dtor$0@?0???0sentry@?$basic_ostream@DU?$char_traits@D@std@@@std@@QEAA@AEAV12@@Z@4HA
xdata	ENDS
;	COMDAT CONST
CONST	SEGMENT
$cppxdata$??0sentry@?$basic_ostream@DU?$char_traits@D@std@@@std@@QEAA@AEAV12@@Z DQ 00000000119930522r ; 2.33398e-314
	DD	imagerel $stateUnwindMap$??0sentry@?$basic_ostream@DU?$char_traits@D@std@@@std@@QEAA@AEAV12@@Z
	DQ	00000000000000000r		; 0
	DD	02H
	DD	imagerel $ip2state$??0sentry@?$basic_ostream@DU?$char_traits@D@std@@@std@@QEAA@AEAV12@@Z
	DQ	00000000000000020r		; 1.58101e-322
	DD	01H
CONST	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??0sentry@?$basic_ostream@DU?$char_traits@D@std@@@std@@QEAA@AEAV12@@Z DD 041811H
	DD	093418H
	DD	07006520aH
	DD	imagerel __CxxFrameHandler3
	DD	imagerel $cppxdata$??0sentry@?$basic_ostream@DU?$char_traits@D@std@@@std@@QEAA@AEAV12@@Z
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?_Tidy@?$vector@PEAVbus_device@@V?$allocator@PEAVbus_device@@@std@@@std@@AEAAXXZ DD 020601H
	DD	030023206H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$ip2state$??1_Sentry_base@?$basic_ostream@DU?$char_traits@D@std@@@std@@QEAA@XZ DD imagerel ??1_Sentry_base@?$basic_ostream@DU?$char_traits@D@std@@@std@@QEAA@XZ+36
	DD	0ffffffffH
xdata	ENDS
;	COMDAT CONST
CONST	SEGMENT
$cppxdata$??1_Sentry_base@?$basic_ostream@DU?$char_traits@D@std@@@std@@QEAA@XZ DQ 00000000019930522r ; 2.11987e-315
	DQ	00000000000000000r		; 0
	DQ	00000000100000000r		; 2.122e-314
	DD	imagerel $ip2state$??1_Sentry_base@?$basic_ostream@DU?$char_traits@D@std@@@std@@QEAA@XZ
	DQ	00000000000000020r		; 1.58101e-322
	DD	05H
CONST	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??1_Sentry_base@?$basic_ostream@DU?$char_traits@D@std@@@std@@QEAA@XZ DD 010d19H
	DD	06204H
	DD	imagerel __CxxFrameHandler3
	DD	imagerel $cppxdata$??1_Sentry_base@?$basic_ostream@DU?$char_traits@D@std@@@std@@QEAA@XZ
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??0_Sentry_base@?$basic_ostream@DU?$char_traits@D@std@@@std@@QEAA@AEAV12@@Z DD 020601H
	DD	030023206H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?deallocate@?$allocator@PEAVbus_device@@@std@@QEAAXQEAPEAVbus_device@@_K@Z DD 010401H
	DD	04204H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?catch$4@?0???$?6U?$char_traits@D@std@@@std@@YAAEAV?$basic_ostream@DU?$char_traits@D@std@@@0@AEAV10@PEBD@Z@4HA DD 020a19H
	DD	05006320aH
	DD	imagerel __CxxFrameHandler3
	DD	imagerel $cppxdata$??$?6U?$char_traits@D@std@@@std@@YAAEAV?$basic_ostream@DU?$char_traits@D@std@@@0@AEAV10@PEBD@Z
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$ip2state$??$?6U?$char_traits@D@std@@@std@@YAAEAV?$basic_ostream@DU?$char_traits@D@std@@@0@AEAV10@PEBD@Z DD imagerel ??$?6U?$char_traits@D@std@@@std@@YAAEAV?$basic_ostream@DU?$char_traits@D@std@@@0@AEAV10@PEBD@Z+118
	DD	0ffffffffH
	DD	imagerel ??$?6U?$char_traits@D@std@@@std@@YAAEAV?$basic_ostream@DU?$char_traits@D@std@@@0@AEAV10@PEBD@Z+163
	DD	00H
	DD	imagerel ??$?6U?$char_traits@D@std@@@std@@YAAEAV?$basic_ostream@DU?$char_traits@D@std@@@0@AEAV10@PEBD@Z+246
	DD	02H
	DD	imagerel ??$?6U?$char_traits@D@std@@@std@@YAAEAV?$basic_ostream@DU?$char_traits@D@std@@@0@AEAV10@PEBD@Z+357
	DD	01H
	DD	imagerel ??$?6U?$char_traits@D@std@@@std@@YAAEAV?$basic_ostream@DU?$char_traits@D@std@@@0@AEAV10@PEBD@Z+398
	DD	04H
	DD	imagerel ??$?6U?$char_traits@D@std@@@std@@YAAEAV?$basic_ostream@DU?$char_traits@D@std@@@0@AEAV10@PEBD@Z+418
	DD	05H
	DD	imagerel ??$?6U?$char_traits@D@std@@@std@@YAAEAV?$basic_ostream@DU?$char_traits@D@std@@@0@AEAV10@PEBD@Z+443
	DD	0ffffffffH
	DD	imagerel ?catch$4@?0???$?6U?$char_traits@D@std@@@std@@YAAEAV?$basic_ostream@DU?$char_traits@D@std@@@0@AEAV10@PEBD@Z@4HA+35
	DD	03H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$handlerMap$0$??$?6U?$char_traits@D@std@@@std@@YAAEAV?$basic_ostream@DU?$char_traits@D@std@@@0@AEAV10@PEBD@Z DD 040H
	DD	00H
	DD	00H
	DD	imagerel ?catch$4@?0???$?6U?$char_traits@D@std@@@std@@YAAEAV?$basic_ostream@DU?$char_traits@D@std@@@0@AEAV10@PEBD@Z@4HA
	DD	038H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$tryMap$??$?6U?$char_traits@D@std@@@std@@YAAEAV?$basic_ostream@DU?$char_traits@D@std@@@0@AEAV10@PEBD@Z DD 02H
	DD	02H
	DD	03H
	DD	01H
	DD	imagerel $handlerMap$0$??$?6U?$char_traits@D@std@@@std@@YAAEAV?$basic_ostream@DU?$char_traits@D@std@@@0@AEAV10@PEBD@Z
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$stateUnwindMap$??$?6U?$char_traits@D@std@@@std@@YAAEAV?$basic_ostream@DU?$char_traits@D@std@@@0@AEAV10@PEBD@Z DD 0ffffffffH
	DD	imagerel ?dtor$1@?0???$?6U?$char_traits@D@std@@@std@@YAAEAV?$basic_ostream@DU?$char_traits@D@std@@@0@AEAV10@PEBD@Z@4HA
	DD	0ffffffffH
	DD	imagerel ?dtor$0@?0???$?6U?$char_traits@D@std@@@std@@YAAEAV?$basic_ostream@DU?$char_traits@D@std@@@0@AEAV10@PEBD@Z@4HA
	DD	01H
	DD	00H
	DD	01H
	DD	00H
	DD	0ffffffffH
	DD	imagerel __std_terminate
	DD	04H
	DD	imagerel __std_terminate
xdata	ENDS
;	COMDAT CONST
CONST	SEGMENT
$cppxdata$??$?6U?$char_traits@D@std@@@std@@YAAEAV?$basic_ostream@DU?$char_traits@D@std@@@0@AEAV10@PEBD@Z DQ 00000000619930522r ; 1.2944e-313
	DD	imagerel $stateUnwindMap$??$?6U?$char_traits@D@std@@@std@@YAAEAV?$basic_ostream@DU?$char_traits@D@std@@@0@AEAV10@PEBD@Z
	DD	01H
	DD	imagerel $tryMap$??$?6U?$char_traits@D@std@@@std@@YAAEAV?$basic_ostream@DU?$char_traits@D@std@@@0@AEAV10@PEBD@Z
	DD	08H
	DD	imagerel $ip2state$??$?6U?$char_traits@D@std@@@std@@YAAEAV?$basic_ostream@DU?$char_traits@D@std@@@0@AEAV10@PEBD@Z
	DQ	00000000000000020r		; 1.58101e-322
	DD	01H
CONST	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??$?6U?$char_traits@D@std@@@std@@YAAEAV?$basic_ostream@DU?$char_traits@D@std@@@0@AEAV10@PEBD@Z DD 081f19H
	DD	0f341fH
	DD	0f00d7211H
	DD	0c009e00bH
	DD	060067007H
	DD	imagerel __CxxFrameHandler3
	DD	imagerel $cppxdata$??$?6U?$char_traits@D@std@@@std@@YAAEAV?$basic_ostream@DU?$char_traits@D@std@@@0@AEAV10@PEBD@Z
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??$endl@DU?$char_traits@D@std@@@std@@YAAEAV?$basic_ostream@DU?$char_traits@D@std@@@0@AEAV10@@Z DD 020601H
	DD	030023206H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??$_Move_unchecked@PEAPEAVbus_device@@PEAPEAV1@@std@@YAPEAPEAVbus_device@@PEAPEAV1@00@Z DD 040a01H
	DD	09340aH
	DD	07006320aH
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$chain$5$??$_Emplace_reallocate@AEBQEAVbus_device@@@?$vector@PEAVbus_device@@V?$allocator@PEAVbus_device@@@std@@@std@@QEAAPEAPEAVbus_device@@QEAPEAV2@AEBQEAV2@@Z DD 021H
	DD	imagerel $LN338@Emplace_re
	DD	imagerel $LN338@Emplace_re+70
	DD	imagerel $unwind$??$_Emplace_reallocate@AEBQEAVbus_device@@@?$vector@PEAVbus_device@@V?$allocator@PEAVbus_device@@@std@@@std@@QEAAPEAPEAVbus_device@@QEAPEAV2@AEBQEAV2@@Z
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$chain$4$??$_Emplace_reallocate@AEBQEAVbus_device@@@?$vector@PEAVbus_device@@V?$allocator@PEAVbus_device@@@std@@@std@@QEAAPEAPEAVbus_device@@QEAPEAV2@AEBQEAV2@@Z DD 060021H
	DD	04f400H
	DD	0d6400H
	DD	0c3400H
	DD	imagerel $LN338@Emplace_re
	DD	imagerel $LN338@Emplace_re+70
	DD	imagerel $unwind$??$_Emplace_reallocate@AEBQEAVbus_device@@@?$vector@PEAVbus_device@@V?$allocator@PEAVbus_device@@@std@@@std@@QEAAPEAPEAVbus_device@@QEAPEAV2@AEBQEAV2@@Z
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$chain$2$??$_Emplace_reallocate@AEBQEAVbus_device@@@?$vector@PEAVbus_device@@V?$allocator@PEAVbus_device@@@std@@@std@@QEAAPEAPEAVbus_device@@QEAPEAV2@AEBQEAV2@@Z DD 063821H
	DD	0c3438H
	DD	04f415H
	DD	0d6405H
	DD	imagerel $LN338@Emplace_re
	DD	imagerel $LN338@Emplace_re+70
	DD	imagerel $unwind$??$_Emplace_reallocate@AEBQEAVbus_device@@@?$vector@PEAVbus_device@@V?$allocator@PEAVbus_device@@@std@@@std@@QEAAPEAPEAVbus_device@@QEAPEAV2@AEBQEAV2@@Z
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??$_Emplace_reallocate@AEBQEAVbus_device@@@?$vector@PEAVbus_device@@V?$allocator@PEAVbus_device@@@std@@@std@@QEAAPEAPEAVbus_device@@QEAPEAV2@AEBQEAV2@@Z DD 050b01H
	DD	0e007420bH
	DD	07003c005H
	DD	05002H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??$_Allocate@$0BA@U_Default_allocate_traits@std@@$0A@@std@@YAPEAX_K@Z DD 010401H
	DD	04204H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??$_Deallocate@$0BA@$0A@@std@@YAXPEAX_K@Z DD 010401H
	DD	04204H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?_Xlength@?$vector@PEAVbus_device@@V?$allocator@PEAVbus_device@@@std@@@std@@CAXXZ DD 010401H
	DD	04204H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?_Change_array@?$vector@PEAVbus_device@@V?$allocator@PEAVbus_device@@@std@@@std@@AEAAXQEAPEAVbus_device@@_K1@Z DD 081401H
	DD	096414H
	DD	085414H
	DD	073414H
	DD	070103214H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?_Umove_if_noexcept@?$vector@PEAVbus_device@@V?$allocator@PEAVbus_device@@@std@@@std@@AEAAXPEAPEAVbus_device@@00@Z DD 011319H
	DD	06204H
	DD	imagerel __GSHandlerCheck
	DD	020H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?_Umove@?$vector@PEAVbus_device@@V?$allocator@PEAVbus_device@@@std@@@std@@AEAAPEAPEAVbus_device@@PEAPEAV3@00@Z DD 040a01H
	DD	06340aH
	DD	07006320aH
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?allocate@?$allocator@PEAVbus_device@@@std@@QEAAPEAPEAVbus_device@@_K@Z DD 010401H
	DD	04204H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??$_Move_unchecked1@PEAPEAVbus_device@@PEAPEAV1@@std@@YAPEAPEAVbus_device@@PEAPEAV1@00U_Trivially_copyable_ptr_iterator_tag@0@@Z DD 040a01H
	DD	06340aH
	DD	07006320aH
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??$_Allocate_manually_vector_aligned@U_Default_allocate_traits@std@@@std@@YAPEAX_K@Z DD 010401H
	DD	04204H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??$_Uninitialized_move@PEAPEAVbus_device@@PEAPEAV1@V?$allocator@PEAVbus_device@@@std@@@std@@YAPEAPEAVbus_device@@QEAPEAV1@0PEAPEAV1@AEAV?$allocator@PEAVbus_device@@@0@@Z DD 040a01H
	DD	09340aH
	DD	07006320aH
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??$_Copy_memmove@PEAPEAVbus_device@@PEAPEAV1@@std@@YAPEAPEAVbus_device@@PEAPEAV1@00@Z DD 040a01H
	DD	06340aH
	DD	07006320aH
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??$_Uninitialized_move_al_unchecked@PEAVbus_device@@PEAV1@V?$allocator@PEAVbus_device@@@std@@@std@@YAPEAPEAVbus_device@@QEAPEAV1@00AEAV?$allocator@PEAVbus_device@@@0@U_Really_trivial_ptr_iterator_tag@0@U?$integral_constant@_N$00@0@@Z DD 040a01H
	DD	06340aH
	DD	07006320aH
END
