; Listing generated by Microsoft (R) Optimizing Compiler Version 19.16.27050.0 

include listing.inc

INCLUDELIB OLDNAMES

PUBLIC	??_C@_0BO@DEJMAFNF@Denver?5blargg?50x6000?5debugger@ ; `string'
PUBLIC	??_C@_0CM@IAEODJIP@Device?5that?5does?52?5clocks?5per?5c@ ; `string'
PUBLIC	??_R2bogusdevice@@8				; bogusdevice::`RTTI Base Class Array'
PUBLIC	??_R2debug6k@@8					; debug6k::`RTTI Base Class Array'
PUBLIC	??_R1A@?0A@EA@bogusdevice@@8			; bogusdevice::`RTTI Base Class Descriptor at (0,-1,0,64)'
PUBLIC	??_R1A@?0A@EA@debug6k@@8			; debug6k::`RTTI Base Class Descriptor at (0,-1,0,64)'
PUBLIC	??_R3bogusdevice@@8				; bogusdevice::`RTTI Class Hierarchy Descriptor'
PUBLIC	??_R0?AVbogusdevice@@@8				; bogusdevice `RTTI Type Descriptor'
PUBLIC	??_R3debug6k@@8					; debug6k::`RTTI Class Hierarchy Descriptor'
PUBLIC	??_R0?AVdebug6k@@@8				; debug6k `RTTI Type Descriptor'
PUBLIC	??_R4bogusdevice@@6B@				; bogusdevice::`RTTI Complete Object Locator'
PUBLIC	??_R4debug6k@@6B@				; debug6k::`RTTI Complete Object Locator'
PUBLIC	??_7bogusdevice@@6B@				; bogusdevice::`vftable'
PUBLIC	??_7debug6k@@6B@				; debug6k::`vftable'
;	COMDAT ??_7debug6k@@6B@
CONST	SEGMENT
??_7debug6k@@6B@ DQ FLAT:??_R4debug6k@@6B@		; debug6k::`vftable'
	DQ	FLAT:?rundevice@device@@UEAAHH@Z
	DQ	FLAT:?dma@device@@UEAAXPEAE_N1@Z
	DQ	FLAT:??_Edebug6k@@UEAAPEAXI@Z
	DQ	FLAT:?write@debug6k@@UEAAXHHE@Z
	DQ	FLAT:?read@bus_device@@UEAAEHH@Z
CONST	ENDS
;	COMDAT ??_7bogusdevice@@6B@
CONST	SEGMENT
??_7bogusdevice@@6B@ DQ FLAT:??_R4bogusdevice@@6B@	; bogusdevice::`vftable'
	DQ	FLAT:?rundevice@bogusdevice@@UEAAHH@Z
	DQ	FLAT:?dma@device@@UEAAXPEAE_N1@Z
CONST	ENDS
;	COMDAT ??_R4debug6k@@6B@
rdata$r	SEGMENT
??_R4debug6k@@6B@ DD 01H				; debug6k::`RTTI Complete Object Locator'
	DD	00H
	DD	00H
	DD	imagerel ??_R0?AVdebug6k@@@8
	DD	imagerel ??_R3debug6k@@8
	DD	imagerel ??_R4debug6k@@6B@
rdata$r	ENDS
;	COMDAT ??_R4bogusdevice@@6B@
rdata$r	SEGMENT
??_R4bogusdevice@@6B@ DD 01H				; bogusdevice::`RTTI Complete Object Locator'
	DD	00H
	DD	00H
	DD	imagerel ??_R0?AVbogusdevice@@@8
	DD	imagerel ??_R3bogusdevice@@8
	DD	imagerel ??_R4bogusdevice@@6B@
rdata$r	ENDS
;	COMDAT ??_R0?AVdebug6k@@@8
data$r	SEGMENT
??_R0?AVdebug6k@@@8 DQ FLAT:??_7type_info@@6B@		; debug6k `RTTI Type Descriptor'
	DQ	0000000000000000H
	DB	'.?AVdebug6k@@', 00H
data$r	ENDS
;	COMDAT ??_R3debug6k@@8
rdata$r	SEGMENT
??_R3debug6k@@8 DD 00H					; debug6k::`RTTI Class Hierarchy Descriptor'
	DD	00H
	DD	03H
	DD	imagerel ??_R2debug6k@@8
rdata$r	ENDS
;	COMDAT ??_R0?AVbogusdevice@@@8
data$r	SEGMENT
??_R0?AVbogusdevice@@@8 DQ FLAT:??_7type_info@@6B@	; bogusdevice `RTTI Type Descriptor'
	DQ	0000000000000000H
	DB	'.?AVbogusdevice@@', 00H
data$r	ENDS
;	COMDAT ??_R3bogusdevice@@8
rdata$r	SEGMENT
??_R3bogusdevice@@8 DD 00H				; bogusdevice::`RTTI Class Hierarchy Descriptor'
	DD	00H
	DD	02H
	DD	imagerel ??_R2bogusdevice@@8
rdata$r	ENDS
;	COMDAT ??_R1A@?0A@EA@debug6k@@8
rdata$r	SEGMENT
??_R1A@?0A@EA@debug6k@@8 DD imagerel ??_R0?AVdebug6k@@@8 ; debug6k::`RTTI Base Class Descriptor at (0,-1,0,64)'
	DD	02H
	DD	00H
	DD	0ffffffffH
	DD	00H
	DD	040H
	DD	imagerel ??_R3debug6k@@8
rdata$r	ENDS
;	COMDAT ??_R1A@?0A@EA@bogusdevice@@8
rdata$r	SEGMENT
??_R1A@?0A@EA@bogusdevice@@8 DD imagerel ??_R0?AVbogusdevice@@@8 ; bogusdevice::`RTTI Base Class Descriptor at (0,-1,0,64)'
	DD	01H
	DD	00H
	DD	0ffffffffH
	DD	00H
	DD	040H
	DD	imagerel ??_R3bogusdevice@@8
rdata$r	ENDS
;	COMDAT ??_R2debug6k@@8
rdata$r	SEGMENT
??_R2debug6k@@8 DD imagerel ??_R1A@?0A@EA@debug6k@@8	; debug6k::`RTTI Base Class Array'
	DD	imagerel ??_R1A@?0A@EA@bus_device@@8
	DD	imagerel ??_R1A@?0A@EA@device@@8
	ORG $+3
rdata$r	ENDS
;	COMDAT ??_R2bogusdevice@@8
rdata$r	SEGMENT
??_R2bogusdevice@@8 DD imagerel ??_R1A@?0A@EA@bogusdevice@@8 ; bogusdevice::`RTTI Base Class Array'
	DD	imagerel ??_R1A@?0A@EA@device@@8
	ORG $+3
rdata$r	ENDS
;	COMDAT ??_C@_0CM@IAEODJIP@Device?5that?5does?52?5clocks?5per?5c@
CONST	SEGMENT
??_C@_0CM@IAEODJIP@Device?5that?5does?52?5clocks?5per?5c@ DB 'Device that'
	DB	' does 2 clocks per clock request', 00H	; `string'
CONST	ENDS
;	COMDAT ??_C@_0BO@DEJMAFNF@Denver?5blargg?50x6000?5debugger@
CONST	SEGMENT
??_C@_0BO@DEJMAFNF@Denver?5blargg?50x6000?5debugger@ DB 'Denver blargg 0x'
	DB	'6000 debugger', 00H				; `string'
PUBLIC	??$?6U?$char_traits@D@std@@@std@@YAAEAV?$basic_ostream@DU?$char_traits@D@std@@@0@AEAV10@D@Z ; std::operator<<<std::char_traits<char> >
PUBLIC	??$?6U?$char_traits@D@std@@@std@@YAAEAV?$basic_ostream@DU?$char_traits@D@std@@@0@AEAV10@E@Z ; std::operator<<<std::char_traits<char> >
PUBLIC	?write@debug6k@@UEAAXHHE@Z			; debug6k::write
PUBLIC	??1debug6k@@UEAA@XZ				; debug6k::~debug6k
PUBLIC	??_Gdebug6k@@UEAAPEAXI@Z			; debug6k::`scalar deleting destructor'
EXTRN	??_Edebug6k@@UEAAPEAXI@Z:PROC			; debug6k::`vector deleting destructor'
;	COMDAT pdata
pdata	SEGMENT
$pdata$??$?6U?$char_traits@D@std@@@std@@YAAEAV?$basic_ostream@DU?$char_traits@D@std@@@0@AEAV10@D@Z DD imagerel $LN108@operator
	DD	imagerel $LN108@operator+445
	DD	imagerel $unwind$??$?6U?$char_traits@D@std@@@std@@YAAEAV?$basic_ostream@DU?$char_traits@D@std@@@0@AEAV10@D@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?catch$4@?0???$?6U?$char_traits@D@std@@@std@@YAAEAV?$basic_ostream@DU?$char_traits@D@std@@@0@AEAV10@D@Z@4HA DD imagerel ?catch$4@?0???$?6U?$char_traits@D@std@@@std@@YAAEAV?$basic_ostream@DU?$char_traits@D@std@@@0@AEAV10@D@Z@4HA
	DD	imagerel ?catch$4@?0???$?6U?$char_traits@D@std@@@std@@YAAEAV?$basic_ostream@DU?$char_traits@D@std@@@0@AEAV10@D@Z@4HA+56
	DD	imagerel $unwind$?catch$4@?0???$?6U?$char_traits@D@std@@@std@@YAAEAV?$basic_ostream@DU?$char_traits@D@std@@@0@AEAV10@D@Z@4HA
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??_Gdebug6k@@UEAAPEAXI@Z DD imagerel $LN15@scalar
	DD	imagerel $LN15@scalar+67
	DD	imagerel $unwind$??_Gdebug6k@@UEAAPEAXI@Z
;	COMDAT xdata
xdata	SEGMENT
$unwind$??_Gdebug6k@@UEAAPEAXI@Z DD 040a01H
	DD	06340aH
	DD	07006320aH
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?catch$4@?0???$?6U?$char_traits@D@std@@@std@@YAAEAV?$basic_ostream@DU?$char_traits@D@std@@@0@AEAV10@D@Z@4HA DD 020a19H
	DD	05006320aH
	DD	imagerel __CxxFrameHandler3
	DD	imagerel $cppxdata$??$?6U?$char_traits@D@std@@@std@@YAAEAV?$basic_ostream@DU?$char_traits@D@std@@@0@AEAV10@D@Z
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$ip2state$??$?6U?$char_traits@D@std@@@std@@YAAEAV?$basic_ostream@DU?$char_traits@D@std@@@0@AEAV10@D@Z DD imagerel ??$?6U?$char_traits@D@std@@@std@@YAAEAV?$basic_ostream@DU?$char_traits@D@std@@@0@AEAV10@D@Z+75
	DD	0ffffffffH
	DD	imagerel ??$?6U?$char_traits@D@std@@@std@@YAAEAV?$basic_ostream@DU?$char_traits@D@std@@@0@AEAV10@D@Z+113
	DD	00H
	DD	imagerel ??$?6U?$char_traits@D@std@@@std@@YAAEAV?$basic_ostream@DU?$char_traits@D@std@@@0@AEAV10@D@Z+218
	DD	02H
	DD	imagerel ??$?6U?$char_traits@D@std@@@std@@YAAEAV?$basic_ostream@DU?$char_traits@D@std@@@0@AEAV10@D@Z+323
	DD	01H
	DD	imagerel ??$?6U?$char_traits@D@std@@@std@@YAAEAV?$basic_ostream@DU?$char_traits@D@std@@@0@AEAV10@D@Z+380
	DD	04H
	DD	imagerel ??$?6U?$char_traits@D@std@@@std@@YAAEAV?$basic_ostream@DU?$char_traits@D@std@@@0@AEAV10@D@Z+400
	DD	05H
	DD	imagerel ??$?6U?$char_traits@D@std@@@std@@YAAEAV?$basic_ostream@DU?$char_traits@D@std@@@0@AEAV10@D@Z+424
	DD	0ffffffffH
	DD	imagerel ?catch$4@?0???$?6U?$char_traits@D@std@@@std@@YAAEAV?$basic_ostream@DU?$char_traits@D@std@@@0@AEAV10@D@Z@4HA+35
	DD	03H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$handlerMap$0$??$?6U?$char_traits@D@std@@@std@@YAAEAV?$basic_ostream@DU?$char_traits@D@std@@@0@AEAV10@D@Z DD 040H
	DD	00H
	DD	00H
	DD	imagerel ?catch$4@?0???$?6U?$char_traits@D@std@@@std@@YAAEAV?$basic_ostream@DU?$char_traits@D@std@@@0@AEAV10@D@Z@4HA
	DD	038H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$tryMap$??$?6U?$char_traits@D@std@@@std@@YAAEAV?$basic_ostream@DU?$char_traits@D@std@@@0@AEAV10@D@Z DD 02H
	DD	02H
	DD	03H
	DD	01H
	DD	imagerel $handlerMap$0$??$?6U?$char_traits@D@std@@@std@@YAAEAV?$basic_ostream@DU?$char_traits@D@std@@@0@AEAV10@D@Z
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$stateUnwindMap$??$?6U?$char_traits@D@std@@@std@@YAAEAV?$basic_ostream@DU?$char_traits@D@std@@@0@AEAV10@D@Z DD 0ffffffffH
	DD	imagerel ?dtor$1@?0???$?6U?$char_traits@D@std@@@std@@YAAEAV?$basic_ostream@DU?$char_traits@D@std@@@0@AEAV10@D@Z@4HA
	DD	0ffffffffH
	DD	imagerel ?dtor$0@?0???$?6U?$char_traits@D@std@@@std@@YAAEAV?$basic_ostream@DU?$char_traits@D@std@@@0@AEAV10@D@Z@4HA
	DD	01H
	DD	00H
	DD	01H
	DD	00H
	DD	0ffffffffH
	DD	imagerel __std_terminate
	DD	04H
	DD	imagerel __std_terminate
xdata	ENDS
;	COMDAT CONST
CONST	SEGMENT
$cppxdata$??$?6U?$char_traits@D@std@@@std@@YAAEAV?$basic_ostream@DU?$char_traits@D@std@@@0@AEAV10@D@Z DQ 00000000619930522r ; 1.2944e-313
	DD	imagerel $stateUnwindMap$??$?6U?$char_traits@D@std@@@std@@YAAEAV?$basic_ostream@DU?$char_traits@D@std@@@0@AEAV10@D@Z
	DD	01H
	DD	imagerel $tryMap$??$?6U?$char_traits@D@std@@@std@@YAAEAV?$basic_ostream@DU?$char_traits@D@std@@@0@AEAV10@D@Z
	DD	08H
	DD	imagerel $ip2state$??$?6U?$char_traits@D@std@@@std@@YAAEAV?$basic_ostream@DU?$char_traits@D@std@@@0@AEAV10@D@Z
	DQ	00000000000000020r		; 1.58101e-322
	DD	01H
CONST	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??$?6U?$char_traits@D@std@@@std@@YAAEAV?$basic_ostream@DU?$char_traits@D@std@@@0@AEAV10@D@Z DD 081f19H
	DD	0f341fH
	DD	0f00d7211H
	DD	0c009e00bH
	DD	060067007H
	DD	imagerel __CxxFrameHandler3
	DD	imagerel $cppxdata$??$?6U?$char_traits@D@std@@@std@@YAAEAV?$basic_ostream@DU?$char_traits@D@std@@@0@AEAV10@D@Z
END
