; Listing generated by Microsoft (R) Optimizing Compiler Version 19.16.27050.0 

include listing.inc

INCLUDELIB OLDNAMES

PUBLIC	??_C@_0BI@NBBEICM@Denver?5NES?5mainram?5?$CI2k?$CJ@ ; `string'
PUBLIC	??_R2mainram@@8					; mainram::`RTTI Base Class Array'
PUBLIC	??_R1A@?0A@EA@mainram@@8			; mainram::`RTTI Base Class Descriptor at (0,-1,0,64)'
PUBLIC	??_R3mainram@@8					; mainram::`RTTI Class Hierarchy Descriptor'
PUBLIC	??_R0?AVmainram@@@8				; mainram `RTTI Type Descriptor'
PUBLIC	??_R4mainram@@6B@				; mainram::`RTTI Complete Object Locator'
PUBLIC	??_7mainram@@6B@				; mainram::`vftable'
;	COMDAT ??_7mainram@@6B@
CONST	SEGMENT
??_7mainram@@6B@ DQ FLAT:??_R4mainram@@6B@		; mainram::`vftable'
	DQ	FLAT:?rundevice@device@@UEAAHH@Z
	DQ	FLAT:?dma@device@@UEAAXPEAE_N1@Z
	DQ	FLAT:??_Emainram@@UEAAPEAXI@Z
	DQ	FLAT:?write@mainram@@UEAAXHHE@Z
	DQ	FLAT:?read@mainram@@UEAAEHH@Z
CONST	ENDS
;	COMDAT ??_R4mainram@@6B@
rdata$r	SEGMENT
??_R4mainram@@6B@ DD 01H				; mainram::`RTTI Complete Object Locator'
	DD	00H
	DD	00H
	DD	imagerel ??_R0?AVmainram@@@8
	DD	imagerel ??_R3mainram@@8
	DD	imagerel ??_R4mainram@@6B@
rdata$r	ENDS
;	COMDAT ??_R0?AVmainram@@@8
data$r	SEGMENT
??_R0?AVmainram@@@8 DQ FLAT:??_7type_info@@6B@		; mainram `RTTI Type Descriptor'
	DQ	0000000000000000H
	DB	'.?AVmainram@@', 00H
data$r	ENDS
;	COMDAT ??_R3mainram@@8
rdata$r	SEGMENT
??_R3mainram@@8 DD 00H					; mainram::`RTTI Class Hierarchy Descriptor'
	DD	00H
	DD	03H
	DD	imagerel ??_R2mainram@@8
rdata$r	ENDS
;	COMDAT ??_R1A@?0A@EA@mainram@@8
rdata$r	SEGMENT
??_R1A@?0A@EA@mainram@@8 DD imagerel ??_R0?AVmainram@@@8 ; mainram::`RTTI Base Class Descriptor at (0,-1,0,64)'
	DD	02H
	DD	00H
	DD	0ffffffffH
	DD	00H
	DD	040H
	DD	imagerel ??_R3mainram@@8
rdata$r	ENDS
;	COMDAT ??_R2mainram@@8
rdata$r	SEGMENT
??_R2mainram@@8 DD imagerel ??_R1A@?0A@EA@mainram@@8	; mainram::`RTTI Base Class Array'
	DD	imagerel ??_R1A@?0A@EA@bus_device@@8
	DD	imagerel ??_R1A@?0A@EA@device@@8
	ORG $+3
rdata$r	ENDS
;	COMDAT ??_C@_0BI@NBBEICM@Denver?5NES?5mainram?5?$CI2k?$CJ@
CONST	SEGMENT
??_C@_0BI@NBBEICM@Denver?5NES?5mainram?5?$CI2k?$CJ@ DB 'Denver NES mainra'
	DB	'm (2k)', 00H				; `string'
PUBLIC	?read@mainram@@UEAAEHH@Z			; mainram::read
PUBLIC	?write@mainram@@UEAAXHHE@Z			; mainram::write
PUBLIC	??1mainram@@UEAA@XZ				; mainram::~mainram
PUBLIC	??_Gmainram@@UEAAPEAXI@Z			; mainram::`scalar deleting destructor'
PUBLIC	??0mainram@@QEAA@XZ				; mainram::mainram
EXTRN	??_Emainram@@UEAAPEAXI@Z:PROC			; mainram::`vector deleting destructor'
;	COMDAT pdata
pdata	SEGMENT
$pdata$??1mainram@@UEAA@XZ DD imagerel $LN10@mainram
	DD	imagerel $LN10@mainram+55
	DD	imagerel $unwind$??1mainram@@UEAA@XZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??_Gmainram@@UEAAPEAXI@Z DD imagerel $LN15@scalar
	DD	imagerel $LN15@scalar+87
	DD	imagerel $unwind$??_Gmainram@@UEAAPEAXI@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??0mainram@@QEAA@XZ DD imagerel $LN7@mainram
	DD	imagerel $LN7@mainram+108
	DD	imagerel $unwind$??0mainram@@QEAA@XZ
;	COMDAT xdata
xdata	SEGMENT
$unwind$??0mainram@@QEAA@XZ DD 020601H
	DD	030023206H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??_Gmainram@@UEAAPEAXI@Z DD 040a01H
	DD	06340aH
	DD	07006320aH
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??1mainram@@UEAA@XZ DD 020601H
	DD	030023206H
END
