; Listing generated by Microsoft (R) Optimizing Compiler Version 19.16.27050.0 

include listing.inc

INCLUDELIB OLDNAMES

PUBLIC	??_C@_0BK@HMMLMB@Denver?5UxROM?5?$CImapper?5002?$CJ@ ; `string'
PUBLIC	??_R2uxrom@@8					; uxrom::`RTTI Base Class Array'
PUBLIC	??_R1A@?0A@EA@uxrom@@8				; uxrom::`RTTI Base Class Descriptor at (0,-1,0,64)'
PUBLIC	??_R3uxrom@@8					; uxrom::`RTTI Class Hierarchy Descriptor'
PUBLIC	??_R0?AVuxrom@@@8				; uxrom `RTTI Type Descriptor'
PUBLIC	??_R4uxrom@@6B@					; uxrom::`RTTI Complete Object Locator'
PUBLIC	??_7uxrom@@6B@					; uxrom::`vftable'
;	COMDAT ??_7uxrom@@6B@
CONST	SEGMENT
??_7uxrom@@6B@ DQ FLAT:??_R4uxrom@@6B@			; uxrom::`vftable'
	DQ	FLAT:?rundevice@device@@UEAAHH@Z
	DQ	FLAT:?dma@device@@UEAAXPEAE_N1@Z
	DQ	FLAT:??_Euxrom@@UEAAPEAXI@Z
	DQ	FLAT:?write@uxrom@@UEAAXHHE@Z
	DQ	FLAT:?read@uxrom@@UEAAEHH@Z
	DQ	FLAT:?set_rom_data@uxrom@@UEAAXPEAE_K@Z
CONST	ENDS
;	COMDAT ??_R4uxrom@@6B@
rdata$r	SEGMENT
??_R4uxrom@@6B@ DD 01H					; uxrom::`RTTI Complete Object Locator'
	DD	00H
	DD	00H
	DD	imagerel ??_R0?AVuxrom@@@8
	DD	imagerel ??_R3uxrom@@8
	DD	imagerel ??_R4uxrom@@6B@
rdata$r	ENDS
;	COMDAT ??_R0?AVuxrom@@@8
data$r	SEGMENT
??_R0?AVuxrom@@@8 DQ FLAT:??_7type_info@@6B@		; uxrom `RTTI Type Descriptor'
	DQ	0000000000000000H
	DB	'.?AVuxrom@@', 00H
data$r	ENDS
;	COMDAT ??_R3uxrom@@8
rdata$r	SEGMENT
??_R3uxrom@@8 DD 00H					; uxrom::`RTTI Class Hierarchy Descriptor'
	DD	00H
	DD	04H
	DD	imagerel ??_R2uxrom@@8
rdata$r	ENDS
;	COMDAT ??_R1A@?0A@EA@uxrom@@8
rdata$r	SEGMENT
??_R1A@?0A@EA@uxrom@@8 DD imagerel ??_R0?AVuxrom@@@8	; uxrom::`RTTI Base Class Descriptor at (0,-1,0,64)'
	DD	03H
	DD	00H
	DD	0ffffffffH
	DD	00H
	DD	040H
	DD	imagerel ??_R3uxrom@@8
rdata$r	ENDS
;	COMDAT ??_R2uxrom@@8
rdata$r	SEGMENT
??_R2uxrom@@8 DD imagerel ??_R1A@?0A@EA@uxrom@@8	; uxrom::`RTTI Base Class Array'
	DD	imagerel ??_R1A@?0A@EA@rom@@8
	DD	imagerel ??_R1A@?0A@EA@bus_device@@8
	DD	imagerel ??_R1A@?0A@EA@device@@8
	ORG $+3
rdata$r	ENDS
;	COMDAT ??_C@_0BK@HMMLMB@Denver?5UxROM?5?$CImapper?5002?$CJ@
CONST	SEGMENT
??_C@_0BK@HMMLMB@Denver?5UxROM?5?$CImapper?5002?$CJ@ DB 'Denver UxROM (ma'
	DB	'pper 002)', 00H				; `string'
PUBLIC	??1uxrom@@UEAA@XZ				; uxrom::~uxrom
PUBLIC	??_Guxrom@@UEAAPEAXI@Z				; uxrom::`scalar deleting destructor'
EXTRN	??_Euxrom@@UEAAPEAXI@Z:PROC			; uxrom::`vector deleting destructor'
;	COMDAT pdata
pdata	SEGMENT
$pdata$??_Guxrom@@UEAAPEAXI@Z DD imagerel $LN18@scalar
	DD	imagerel $LN18@scalar+67
	DD	imagerel $unwind$??_Guxrom@@UEAAPEAXI@Z
;	COMDAT xdata
xdata	SEGMENT
$unwind$??_Guxrom@@UEAAPEAXI@Z DD 040a01H
	DD	06340aH
	DD	07006320aH
END
