; Listing generated by Microsoft (R) Optimizing Compiler Version 19.16.27050.0 

include listing.inc

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES

PUBLIC	__@@_PchSym_@00@UfhvihUmrtsglirfhOksryrzmUhlfixvUivklhUwvmevivnfUwvmevivnfUcGEUwvyftUhgwzucOlyq@4B2008FD98C1DD4
;	COMDAT __@@_PchSym_@00@UfhvihUmrtsglirfhOksryrzmUhlfixvUivklhUwvmevivnfUwvmevivnfUcGEUwvyftUhgwzucOlyq@4B2008FD98C1DD4
_BSS	SEGMENT
__@@_PchSym_@00@UfhvihUmrtsglirfhOksryrzmUhlfixvUivklhUwvmevivnfUwvmevivnfUcGEUwvyftUhgwzucOlyq@4B2008FD98C1DD4 DD 01H DUP (?)
_BSS	ENDS
msvcjmc	SEGMENT
__84F95A01_denveremu@pch DB 01H
__D40DD59F_corecrt_stdio_config@h DB 01H
__3AB8031F_corecrt_wstdio@h DB 01H
__A57BBCE6_stdio@h DB 01H
__5DB10197_corecrt_memcpy_s@h DB 01H
__7EC77528_corecrt_wconio@h DB 01H
__5C7715BA_corecrt_wio@h DB 01H
__7A0084B3_corecrt_wstring@h DB 01H
__8AE89E8D_corecrt_wtime@h DB 01H
__3F8BCAED_stat@h DB 01H
__5B5D5F1B_wchar@h DB 01H
__6AB54586_tchar@h DB 01H
msvcjmc	ENDS
PUBLIC	__JustMyCode_Default
; Function compile flags: /Odt
;	COMDAT __JustMyCode_Default
_TEXT	SEGMENT
__JustMyCode_Default PROC				; COMDAT
	ret	0
__JustMyCode_Default ENDP
_TEXT	ENDS
END
